window.L123 = [
  {
    id: 1,
    category: "Cephalosporins: First Generation",
    questionText: "A 45-year-old male is scheduled for an elective inguinal hernia repair. To prevent surgical site infection, primarily caused by skin flora such as *Staphylococcus aureus*, which antibiotic is the preferred agent for surgical prophylaxis administered within 60 minutes of the incision?",
    options: [
      { text: "Ceftriaxone", explanation: "Incorrect. Ceftriaxone is a third-generation cephalosporin with broad gram-negative coverage and is not the first line for surgical prophylaxis targeting skin flora. This would be the correct answer if treating a complicated intra-abdominal infection." },
      { text: "Cefazolin", explanation: "Correct. Cefazolin is a first-generation cephalosporin with excellent activity against MSSA and streptococci (skin flora) and is the standard of care for surgical prophylaxis." },
      { text: "Cefepime", explanation: "Incorrect. Cefepime is a fourth-generation cephalosporin reserved for broad-spectrum hospital-acquired infections, including Pseudomonas. This would be the correct answer if treating nosocomial sepsis." },
      { text: "Vancomycin", explanation: "Incorrect. Vancomycin is reserved for patients with severe beta-lactam allergies or known MRSA colonization, not routine prophylaxis. This would be the correct answer if the patient had a history of anaphylaxis to penicillin." },
      { text: "Cephalexin", explanation: "Incorrect. Cephalexin is an oral first-generation cephalosporin, whereas surgical prophylaxis requires a parenteral agent like Cefazolin. This would be the correct answer if oral prophylaxis was appropriate." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Cefazolin (1st gen) is the workhorse for surgical prophylaxis due to its activity against MSSA and Streptococci. Think 'Ancef for surgery'.",
    pdfPage: 17,
  },
  {
    id: 2,
    category: "Cephalosporins: Adverse Effects",
    questionText: "A neonate born at 32 weeks gestation develops sepsis. The team considers empiric antibiotics. Which cephalosporin is contraindicated in neonates due to the risk of displacing bilirubin from albumin, potentially leading to kernicterus?",
    options: [
      { text: "Cefotaxime", explanation: "Incorrect. Cefotaxime is the preferred cephalosporin for neonatal sepsis as it does not displace bilirubin. This would be the correct answer if asking for the *preferred* agent." },
      { text: "Ceftazidime", explanation: "Incorrect. Ceftazidime is generally safe but used specifically for Pseudomonas concerns. This would be the correct answer if Pseudomonas was suspected." },
      { text: "Ceftriaxone", explanation: "Correct. Ceftriaxone is highly protein-bound and can displace bilirubin, causing kernicterus in neonates. It also precipitates with calcium-containing IV solutions." },
      { text: "Cefepime", explanation: "Incorrect. Cefepime is not typically associated with kernicterus, though renal dosing is important. This would be the correct answer if asking about neurotoxicity in renal failure." },
      { text: "Cefazolin", explanation: "Incorrect. Cefazolin does not cross the blood-brain barrier well enough for meningitis/sepsis treatment but doesn't cause kernicterus. This would be the correct answer if asking about inadequate CNS penetration." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Avoid Ceftriaxone in neonates! It causes biliary sludge and kernicterus. Use Cefotaxime instead.",
    pdfPage: 19,
  },
  {
    id: 3,
    category: "Cephalosporins: Third Generation",
    questionText: "A 22-year-old male presents with purulent urethral discharge. Gram stain reveals Gram-negative diplococci. The CDC recommended treatment for uncomplicated gonococcal infection involves a single intramuscular dose of which agent?",
    options: [
      { text: "Cefixime", explanation: "Incorrect. Oral Cefixime is no longer the first-line recommended empiric therapy due to rising resistance. This would be the correct answer if IM therapy was refused and patient counseling provided." },
      { text: "Ceftriaxone", explanation: "Correct. A single IM dose of Ceftriaxone is the gold standard for treating Neisseria gonorrhoeae." },
      { text: "Azithromycin", explanation: "Incorrect. Azithromycin was previously used as dual therapy but is no longer routinely recommended for gonorrhea monotherapy due to resistance. This would be the correct answer if treating Chlamydia monotherapy." },
      { text: "Cefotaxime", explanation: "Incorrect. While active, Cefotaxime requires multiple doses due to its shorter half-life compared to Ceftriaxone. This would be the correct answer if Ceftriaxone was unavailable." },
      { text: "Doxycycline", explanation: "Incorrect. Doxycycline is used to treat co-infection with Chlamydia, not Gonorrhea itself as a single agent. This would be the correct answer if treating co-infection." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Ceftriaxone is the drug of choice for Gonorrhea. Remember to treat Chlamydia empirically (Doxycycline) if not ruled out.",
    pdfPage: 21,
  },
  {
    id: 4,
    category: "Cephalosporins: Second Generation",
    questionText: "A patient with a history of alcohol use disorder is treated for a pelvic infection with Cefotetan. Several days later, they consume alcohol and develop flushing, nausea, and vomiting. This reaction is due to inhibition of which enzyme?",
    options: [
      { text: "Alcohol dehydrogenase", explanation: "Incorrect. Inhibition of alcohol dehydrogenase prevents alcohol breakdown, but the reaction is due to acetaldehyde buildup. This would be the correct answer if asking about Fomepizole's target." },
      { text: "Aldehyde dehydrogenase", explanation: "Correct. Cefotetan has an N-methylthiotetrazole (NMTT) side chain that inhibits aldehyde dehydrogenase, causing a Disulfiram-like reaction." },
      { text: "Cytochrome P450", explanation: "Incorrect. This is not a CYP450 interaction. This would be the correct answer if asking about Macrolide interactions." },
      { text: "Monoamine oxidase", explanation: "Incorrect. MAO inhibition causes hypertensive crisis with tyramine, not flushing with alcohol. This would be the correct answer if taking Linezolid." },
      { text: "Vitamin K epoxide reductase", explanation: "Incorrect. While Cefotetan can inhibit this enzyme (causing bleeding), it is not the mechanism of the alcohol reaction. This would be the correct answer if asking about hypoprothrombinemia." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Cefotetan and Cefoperazone contain the NMTT side chain, causing Disulfiram-like reactions and hypoprothrombinemia (bleeding risk).",
    pdfPage: 45,
  },
  {
    id: 5,
    category: "Cephalosporins: Fifth Generation",
    questionText: "A 65-year-old patient with hospital-acquired pneumonia has blood cultures positive for MRSA. Which advanced-generation cephalosporin is the only beta-lactam with activity against MRSA?",
    options: [
      { text: "Cefepime", explanation: "Incorrect. Cefepime (4th gen) covers Pseudomonas but NOT MRSA. This would be the correct answer if the pathogen was Pseudomonas." },
      { text: "Ceftaroline", explanation: "Correct. Ceftaroline binds to PBP2a, the altered penicillin-binding protein in MRSA, conferring activity." },
      { text: "Ceftazidime", explanation: "Incorrect. Ceftazidime (3rd gen) covers Pseudomonas but NOT MRSA. This would be the correct answer if the pathogen was Pseudomonas." },
      { text: "Cefiderocol", explanation: "Incorrect. Cefiderocol is a siderophore cephalosporin for MDR Gram-negatives, not primarily for MRSA. This would be the correct answer if treating MDR Acinetobacter." },
      { text: "Ceftriaxone", explanation: "Incorrect. No 3rd generation cephalosporin covers MRSA. This would be the correct answer if treating MSSA." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Ceftaroline is the 'MRSA Cephalosporin'. It binds PBP2a.",
    pdfPage: 14,
  },
  {
    id: 6,
    category: "Monobactams",
    questionText: "A patient with a documented history of anaphylaxis to Penicillin G requires treatment for a Gram-negative bacteremia (Psudeomonas aeruginosa confirmed). Which beta-lactam agent can be safely administered with negligible risk of cross-reactivity?",
    options: [
      { text: "Cefepime", explanation: "Incorrect. While cross-reactivity is low, there is some risk with cephalosporins in patients with anaphylaxis to penicillin. This would be the correct answer if allergy was mild rash." },
      { text: "Meropenem", explanation: "Incorrect. Carbapenems have a low (<1%) but non-zero cross-reactivity. This would be the correct answer if allergy was mild." },
      { text: "Aztreonam", explanation: "Correct. Aztreonam (Monobactam) has a unique structure and virtually no cross-reactivity with penicillins/cephalosporins (except Ceftazidime)." },
      { text: "Piperacillin-Tazobactam", explanation: "Incorrect. This is a penicillin derivative and is contraindicated in anaphylaxis. This would be the correct answer if patient was not allergic to penicillins." },
      { text: "Ceftaroline", explanation: "Incorrect. It is a cephalosporin and carries potential cross-reactivity risk. This would be the correct answer if treating MRSA in non-allergic patient." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Aztreonam is safe for Penicillin-allergic patients! (Note: Avoid if allergy is specifically to Ceftazidime due to identical side chain).",
    pdfPage: 28,
  },
  {
    id: 7,
    category: "Carbapenems: Mechanism",
    questionText: "Imipenem is always co-administered with Cilastatin. What is the primary function of Cilastatin?",
    options: [
      { text: "Increases GI absorption", explanation: "Incorrect. Imipenem is given IV. This would be the correct answer if asking about Clavulanate's effect on Amoxicillin stability (partially)." },
      { text: "Inhibits beta-lactamase", explanation: "Incorrect. Imipenem itself is stable to many beta-lactamases; Cilastatin is not a BLI. This would be the correct answer if asking about Tazobactam." },
      { text: "Inhibits renal dehydropeptidase I", explanation: "Correct. Cilastatin inhibits renal dehydropeptidase I, preventing the degradation of Imipenem in the renal tubules and reducing nephrotoxicity." },
      { text: "Prevents seizures", explanation: "Incorrect. Cilastatin does not prevent seizures; in fact, Imipenem accumulates in renal failure which increases seizure risk. This would be the correct answer if asking about Valproate." },
      { text: "Enhances Gram-positive coverage", explanation: "Incorrect. It affects pharmacokinetics/metabolism, not the antibacterial spectrum. This would be the correct answer if asking about adding Vancomycin." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Imipenem needs Cilastatin to prevent renal breakdown. 'Keep the Imipenem Lastin' with Cilastatin'.",
    pdfPage: 19,
  },
  {
    id: 8,
    category: "Carbapenems: Spectrum",
    questionText: "Which Carbapenem is unique in that it lacks activity against *Pseudomonas aeruginosa* and *Acinetobacter* species, making it suitable for community-acquired intra-abdominal infections but not severe nosocomial pneumonia?",
    options: [
      { text: "Imipenem", explanation: "Incorrect. Imipenem covers Pseudomonas. This would be the correct answer if asking for a drug with seizure risk." },
      { text: "Meropenem", explanation: "Incorrect. Meropenem covers Pseudomonas. This would be the correct answer if asking for a drug with CNS penetration." },
      { text: "Doripenem", explanation: "Incorrect. Doripenem covers Pseudomonas. This would be the correct answer if asking for a potent anti-pseudomonal carbapenem." },
      { text: "Ertapenem", explanation: "Correct. Ertapenem has a narrower spectrum ('Ape' without the 'Pseudomonas') - it does NOT cover Pseudomonas, Acinetobacter, or Enterococcus." },
      { text: "Aztreonam", explanation: "Incorrect. Aztreonam is a monobactam, not a carbapenem, though it does cover Pseudomonas. This would be the correct answer if asking about monobactams." },
    ],
    correctAnswerIndex: 3,
    clinicalPearl: "Ertapenem: The 'Exception' Carbapenem. No Pseudomonas, No Acinetobacter, No Enterococcus (APE).",
    pdfPage: 23,
  },
  {
    id: 9,
    category: "Vancomycin: Adverse Effects",
    questionText: "During a rapid infusion of Vancomycin, a patient develops intense flushing of the face, neck, and upper torso, along with hypotension. What is the mechanism of this reaction?",
    options: [
      { text: "IgE-mediated anaphylaxis", explanation: "Incorrect. Red Man Syndrome is an anaphylactoid reaction, not IgE-mediated. This would be the correct answer if reaction persisted despite slowing infusion." },
      { text: "Direct histamine release from mast cells", explanation: "Correct. 'Red Man Syndrome' (Vancomycin Infusion Reaction) is caused by direct non-immunologic degranulation of mast cells due to rapid infusion." },
      { text: "Type IV hypersensitivity", explanation: "Incorrect. This is a delayed reaction (e.g., DRESS), not immediate flushing. This would be the correct answer if rash appeared days later." },
      { text: "Complement activation", explanation: "Incorrect. Not the primary mechanism. This would be the correct answer if asking about autoimmune hemolysis." },
      { text: "Bradykinin accumulation", explanation: "Incorrect. This is associated with ACE inhibitors (angioedema). This would be the correct answer if patient was on Lisinopril." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Red Man Syndrome is rate-dependent. Slow the infusion rate to treat/prevent it. It is NOT a true allergy.",
    pdfPage: 46,
  },
  {
    id: 10,
    category: "Daptomycin: Mechanism",
    questionText: "Daptomycin is acceptable for treating MRSA bacteremia. What is its unique mechanism of action?",
    options: [
      { text: "Binds D-Ala-D-Ala to block cell wall synthesis", explanation: "Incorrect. This is Vancomycin. This would be the correct answer if asking about Glycopeptides." },
      { text: "Binds PBP2a", explanation: "Incorrect. This is Ceftaroline. This would be the correct answer if asking about 5th Gen Cephalosporins." },
      { text: "Inserts lipid tail into cell membrane causing depolarization", explanation: "Correct. Daptomycin is a cyclic lipopeptide that inserts into the cell membrane, causing rapid depolarization and ion leakage (bactericidal)." },
      { text: "Inhibits protein synthesis at 50S ribosome", explanation: "Incorrect. This describes Linezolid/Macrolides. This would be the correct answer if asking about Linezolid." },
      { text: "Inhibits DNA gyrase", explanation: "Incorrect. This describes Fluoroquinolones. This would be the correct answer if asking about Ciprofloxacin." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Daptomycin disrupts the cell MEMBRANE (depolarization), not the cell wall. It is rapidly bactericidal.",
    pdfPage: 38,
  },
  {
    id: 11,
    category: "Daptomycin: Contraindications",
    questionText: "Why is Daptomycin ineffective and contraindicated for the treatment of *Streptococcus pneumoniae* pneumonia, despite the organism being sensitive in vitro?",
    options: [
      { text: "It cannot penetrate the lung tissue", explanation: "Incorrect. It penetrates, but is inactivated. This would be the correct answer if asking about aminoglycosides (poor lung penetration)." },
      { text: "It is inactivated by pulmonary surfactant", explanation: "Correct. Pulmonary surfactant binds to and inactivates Daptomycin, rendering it useless for alveolar infections." },
      { text: "It is pumped out by efflux pumps in the lung", explanation: "Incorrect. Efflux is a resistance mechanism, not the reason for primary failure in pneumonia. This would be the correct answer if asking about Pseudomonas resistance." },
      { text: "It causes severe pneumonitis", explanation: "Incorrect. While eosinophilic pneumonia is a rare side effect, the reason it's ineffective is inactivation. This would be the correct answer if asking about side effects." },
      { text: "The pH of the lung inhibits the drug", explanation: "Incorrect. Surfactant interaction is the key. This would be the correct answer if asking about aminoglycosides in abscesses." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Never use Daptomycin for Pneumonia! Pulmonary surfactant inactivates it.",
    pdfPage: 39,
  },
  {
    id: 12,
    category: "Vancomycin: Route of Administration",
    questionText: "A patient diagnosed with *Clostridioides difficile* colitis (severe). What is the appropriate route of administration for Vancomycin in this scenario?",
    options: [
      { text: "Intravenous (IV)", explanation: "Incorrect. IV Vancomycin does not cross into the bowel lumen in sufficient levels to treat C. diff colitis. This would be the correct answer if treating bacteremia." },
      { text: "Intramuscular (IM)", explanation: "Incorrect. IM injection is painful and not used for Vanco. This would be the correct answer for Ceftriaxone." },
      { text: "Oral (PO)", explanation: "Correct. Oral Vancomycin is not absorbed systemically, so it reaches very high concentrations in the colon to kill C. diff." },
      { text: "Subcutaneous", explanation: "Incorrect. Not appropriate for Vanco. This would be the correct answer for Insulin." },
      { text: "Inhaled", explanation: "Incorrect. Not used for colitis. This would be the correct answer for Tobramycin in CF." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Oral Vancomycin is ONLY for C. diff. IV Vancomycin is for systemic MRSA infections.",
    pdfPage: 30,
  },
  {
    id: 13,
    category: "Cephalosporins: Fourth Generation",
    questionText: "Cefepime is a broad-spectrum 4th generation cephalosporin. Which feature distinguishes it from 3rd generation agents like Ceftriaxone?",
    options: [
      { text: "Lack of Pseudomonas coverage", explanation: "Incorrect. Cefepime COVERS Pseudomonas. This would be the correct answer for Ceftriaxone." },
      { text: "Activity against MRSA", explanation: "Incorrect. Neither covers MRSA. This would be the correct answer for Ceftaroline." },
      { text: "Better stability against AmpC beta-lactamases", explanation: "Correct. Cefepime is a zwitterion and penetrates Gram-negative outer membranes well; it is also more stable against AmpC beta-lactamases than 3rd gen agents." },
      { text: "Oral bioavailability", explanation: "Incorrect. Cefepime is parenteral only. This would be the correct answer for Cefpodoxime." },
      { text: "Biliary excretion", explanation: "Incorrect. Cefepime is renally excreted. This would be the correct answer for Ceftriaxone." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Cefepime is 'Cef-Prime'. It covers Pseudomonas + improved stability against resistance (AmpC).",
    pdfPage: 9,
  },
  {
    id: 14,
    category: "Cephalosporins: Gen 3 vs Pseudomonas",
    questionText: "Which specific 3rd generation cephalosporin has activity against *Pseudomonas aeruginosa*?",
    options: [
      { text: "Ceftriaxone", explanation: "Incorrect. Ceftriaxone has NO Pseudomonas activity. This would be the correct answer if treating community-acquired pneumonia." },
      { text: "Cefotaxime", explanation: "Incorrect. Cefotaxime has NO Pseudomonas activity. This would be the correct answer if treating meningitis (non-pseudomonal)." },
      { text: "Ceftazidime", explanation: "Correct. Ceftazidime is the only 3rd gen cephalosporin with strong antipseudomonal activity." },
      { text: "Cefdinir", explanation: "Incorrect. Oral 3rd gens don't cover Pseudomonas. This would be the correct answer if treating otitis media." },
      { text: "Cefpodoxime", explanation: "Incorrect. Does not cover Pseudomonas. This would be the correct answer if treating a UTI (non-pseudomonal)." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Ceftazidime = PsEuDomonas (it's a stretch, but remember only Taz/Pime/Zol/Taz cover Pseudomonas among cephs).",
    pdfPage: 9,
  },
  {
    id: 15,
    category: "Vancomycin: Resistance",
    questionText: "Vancomycin-resistant Enterococcus (VRE) mediates resistance via which modification to the peptidoglycan cell wall precursors?",
    options: [
      { text: "Methylation of the ribosome", explanation: "Incorrect. This is macrolide resistance. This would be the correct answer if asking about Erythromycin resistance." },
      { text: "Production of beta-lactamase", explanation: "Incorrect. B-lactamases destroy beta-lactams, they don't affect Vanco. This would be the correct answer if asking about Penicillin resistance." },
      { text: "Modification of D-Ala-D-Ala to D-Ala-D-Lactate", explanation: "Correct. Replacing the terminal D-Alanine with D-Lactate removes the hydrogen bond target for Vancomycin, reducing affinity by 1000-fold." },
      { text: "Thickening of the cell wall", explanation: "Incorrect. This is the mechanism for VISA (Intermediate Staph aureus), not VRE. This would be the correct answer if asking about VISA." },
      { text: "Efflux pumps", explanation: "Incorrect. Not the primary mechanism for VRE. This would be the correct answer for tetracycline resistance." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "VRE Mechanism: D-Ala-D-Ala changes to D-Ala-D-Lactate. Vancomycin can't grab it.",
    pdfPage: 32,
  },
  {
    id: 16,
    category: "Daptomycin: Monitoring",
    questionText: "A patient on prolonged Daptomycin therapy for MRSA osteomyelitis reports muscle pain and tea-colored urine. Which lab value must be monitored weekly in patients on Daptomycin?",
    options: [
      { text: "Serum Creatinine", explanation: "Incorrect. While renally adjusted, CPK is the specific monitor for myopathy. This would be the correct answer for Vancomycin." },
      { text: "Liver Function Tests", explanation: "Incorrect. Daptomycin is not primarily hepatotoxic. This would be the correct answer for Nafcillin." },
      { text: "Creatine Phosphokinase (CPK)", explanation: "Correct. Daptomycin causes myopathy and rhabdomyolysis. Challenge CPK weekly." },
      { text: "Platelet count", explanation: "Incorrect. This is for Linezolid. This would be the correct answer if patient was on Linezolid." },
      { text: "White Blood Cell count", explanation: "Incorrect. Not a specific toxicity monitor. This would be the correct answer for Clozapine." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Daptomycin -> Skeletal Muscle toxicity. Monitor CPK levels.",
    pdfPage: 40,
  },
  {
    id: 17,
    category: "Carbapenems: Side Effects",
    questionText: "Which Carbapenem has the highest associated risk of inducing seizures, particularly in patients with renal failure or underlying CNS pathology?",
    options: [
      { text: "Meropenem", explanation: "Incorrect. Meropenem has a lower seizure risk than Imipenem. This would be the correct answer if Imipenem was unavailable." },
      { text: "Ertapenem", explanation: "Incorrect. Lower seizure risk. This would be the correct answer if used once daily." },
      { text: "Imipenem", explanation: "Correct. Imipenem significantly lowers the seizure threshold, more so than other carbapenems." },
      { text: "Doripenem", explanation: "Incorrect. Lower risk. This would be the correct answer for VAP." },
      { text: "Faropenem", explanation: "Incorrect. An oral penem. This would be the correct answer if asking about oral options." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Imipenem = Seizures. Especially in renal failure.",
    pdfPage: 25,
  },
  {
    id: 18,
    category: "Cephalosporins: Gen 2 Spectrum",
    questionText: "Second-generation cephalosporins like Cefoxitin and Cefotetan are distinguished from first-generation agents by their added coverage of which organism?",
    options: [
      { text: "Pseudomonas aeruginosa", explanation: "Incorrect. Only Gen 3/4. This would be the correct answer for Ceftazidime." },
      { text: "MRSA", explanation: "Incorrect. Only Gen 5. This would be the correct answer for Ceftaroline." },
      { text: "Bacteroides fragilis (Anaerobes)", explanation: "Correct. The 'Cephamycins' (Cefoxitin, Cefotetan) have activity against bowel anaerobes like B. fragilis.", },
      { text: "Enterococcus faecalis", explanation: "Incorrect. Cephalosporins do NOT cover Enterococcus. This would be the correct answer for Ampicillin." },
      { text: "Listeria monocytogenes", explanation: "Incorrect. Cephalosporins do NOT cover Listeria. This would be the correct answer for Ampicillin." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Cefoxitin/Cefotetan are the 'Anaerobic Cephalosporins'. Used for abdominal surgery prophylaxis.",
    pdfPage: 42,
  },
  {
    id: 19,
    category: "Siderophore Cephalosporins",
    questionText: "Cefiderocol mechanism of action involves:",
    options: [
      { text: "Chelating iron to hijack bacterial iron transport systems", explanation: "Correct. Cefiderocol acts as a 'Trojan Horse', binding ferric iron and entering the bacteria via iron transport channels to bypass porin mutations." },
      { text: "Direct membrane depolarization", explanation: "Incorrect. Daptomycin. This would be the correct answer for Daptomycin." },
      { text: "Binding to 30S ribosome", explanation: "Incorrect. Aminoglycosides/Tetracyclines. This would be the correct answer for Gentamicin." },
      { text: "Inhibiting folate synthesis", explanation: "Incorrect. Trimethoprim/Sulfonamides. This would be the correct answer for Bactrim." },
      { text: "Disrupting mycolic acid synthesis", explanation: "Incorrect. Isoniazid. This would be the correct answer for TB treatment." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Cefiderocol = 'Trojan Horse'. Uses iron transport to sneak into difficult Gram-negatives.",
    pdfPage: 14,
  },
  {
    id: 20,
    category: "Cephalosporin Class Gaps",
    questionText: "As a general rule, Cephalosporins (Gen 1-4) are LAME because they lack coverage for:",
    options: [
      { text: "Listeria, Atypicals, MRSA, Enterococcus", explanation: "Correct. LAME mnemonic: L=Listeria, A=Atypicals (Mycoplasma/Chlamydia), M=MRSA (except 5th gen), E=Enterococcus." },
      { text: "Legionella, Anaerobes, Mycobacteria, E. coli", explanation: "Incorrect. Incorrect mnemonic. This would be the correct answer if mnemonic was different." },
      { text: "Lactobacillus, Acinetobacter, Moraxella, Enterobacter", explanation: "Incorrect. Incorrect mnemonic. This would be the correct answer if mnemonic was different." },
      { text: "Listeria, Anaerobes, MRSA, E. coli", explanation: "Incorrect. Incorrect mnemonic. This would be the correct answer if mnemonic was different." },
      { text: "None of the above", explanation: "Incorrect. The first option is correct. This would be the correct answer if no option matched." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Cephs are LAME: No Listeria, No Atypicals, No MRSA (mostly), No Enterococcus!",
    pdfPage: 15,
  },
  {
    id: 21,
    category: "Cephalosporins: First Gen Oral",
    questionText: "An 18-year-old with a simple cellulitis (non-purulent) requires oral antibiotics. Which first-generation cephalosporin is commonly used for this indication?",
    options: [
      { text: "Cefazolin", explanation: "Incorrect. IV/IM only. This would be the correct answer if IV therapy was planned." },
      { text: "Cephalexin", explanation: "Correct. Cephalexin (Keflex) is the oral counterpart to Cefazolin, excellent for MSSA/Strep skin infections." },
      { text: "Cefuroxime", explanation: "Incorrect. Second gen. This would be the correct answer if asking for a 2nd gen." },
      { text: "Cefixime", explanation: "Incorrect. Third gen. This would be the correct answer if asking for a 3rd gen." },
      { text: "Cefdinir", explanation: "Incorrect. Third gen. This would be the correct answer if asking for a 3rd gen." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Cephalexin = Oral Keflex. Simple skin infections.",
    pdfPage: 44,
  },
  {
    id: 22,
    category: "Cephalosporins: Meningitis",
    questionText: "Which two 3rd generation cephalosporins have sufficient BBB penetration to be used for empiric meningitis treatment?",
    options: [
      { text: "Cefazolin & Cephalexin", explanation: "Incorrect. Poor penetration. This would be the correct answer for skin infections." },
      { text: "Ceftriaxone & Cefotaxime", explanation: "Correct. These are the workhorses for neurologic infections." },
      { text: "Ceftazidime & Cefepime", explanation: "Incorrect. Used for nosocomial/Pseudomonal meningitis, but Ceftriaxone/Cefotaxime are the standard community choice. This would be the correct answer for nosocomial meningitis." },
      { text: "Cefoxitin & Cefotetan", explanation: "Incorrect. Poor CNS penetration. This would be the correct answer for abdominal prophylaxis." },
      { text: "Ceftaroline & Ceftobiprole", explanation: "Incorrect. Not first line for empiric meningitis. This would be the correct answer for MRSA meningitis (potentially)." }
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Meningitis? Think Ceftriaxone or Cefotaxime. (Add Vanco for resistant Pneumococc and Ampicillin for Listeria if old/young).",
    pdfPage: 21,
  },
  {
    id: 23,
    category: "Vancomycin: Monitoring",
    questionText: "For severe MRSA infections (like pneumonia or endocarditis), Vancomycin dosing is targeted to achieve an AUC/MIC ratio of:",
    options: [
      { text: "> 100", explanation: "Incorrect. Too low. This would be the correct answer for some Gram-negatives (maybe)." },
      { text: "400 - 600", explanation: "Correct. This range maximizes efficacy while minimizing nephrotoxicity." },
      { text: "< 50", explanation: "Incorrect. Therapeutic failure likely. This would be the correct answer if efficacy was not a concern." },
      { text: "800 - 1000", explanation: "Incorrect. High risk of nephrotoxicity. This would be the correct answer if ignoring safety." },
      { text: "Vancomycin does not require monitoring", explanation: "Incorrect. It has a narrow therapeutic index. This would be the correct answer for Beta-lactams." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Target AUC/MIC 400-600 for serious MRSA infections.",
    pdfPage: 17,
  },
  {
    id: 24,
    category: "Antibiotics: Renal Elimination",
    questionText: "Most beta-lactams require renal dose adjustment. Which cephalosporin is an exception because it is primarily eliminated in the bile?",
    options: [
      { text: "Cefazolin", explanation: "Incorrect. Renally eliminated. This would be the correct answer if GFR was normal." },
      { text: "Ceftriaxone", explanation: "Correct. No renal adjustment needed for Ceftriaxone! Elimination is biliary." },
      { text: "Cefepime", explanation: "Incorrect. Renally eliminated. This would be the correct answer for standard dosing." },
      { text: "Ceftazidime", explanation: "Incorrect. Renally eliminated. This would be the correct answer for Pseudomonas." },
      { text: "Cephalexin", explanation: "Incorrect." }
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Renal failure patient? Ceftriaxone is safe without dose adjustment.",
    pdfPage: 8,
  },
  {
    id: 25,
    category: "Monobactams: Structure",
    questionText: "Aztreonam is structurally distinct from other beta-lactams because:",
    options: [
      { text: "It has two beta-lactam rings", explanation: "Incorrect. No drug has two. This would be the correct answer for a fictional super-drug." },
      { text: "It has a monocyclic beta-lactam ring not fused to another ring", explanation: "Correct. Hence 'Mono-bactam'." },
      { text: "It lacks a beta-lactam ring entirely", explanation: "Incorrect. It IS a beta-lactam, just a monocyclic one. This would be the correct answer for Vancomycin." },
      { text: "It contains a peptide tail", explanation: "Incorrect. This would be the correct answer for Glycopeptides." },
      { text: "It is a glycopeptide", explanation: "Incorrect. This would be the correct answer for Vancomycin." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Monobactam = One ring. (Reference to LOTR is optional but fun).",
    pdfPage: 44,
  },
  {
    id: 26,
    category: "Cephalosporins: Lyme Disease",
    questionText: "A patient with early disseminated Lyme disease (molecularly confirmed) has cardiac conduction abnormalities. IV antibiotic therapy is initiated. Which Cephalosporin is effective for Lyme disease?",
    options: [
      { text: "Cefazolin", explanation: "Incorrect. Cefazolin does not cross the BBB well. This would be the correct answer for skin infections." },
      { text: "Ceftriaxone", explanation: "Correct. Ceftriaxone is the drug of choice for severe/neurologic/cardiac Lyme disease." },
      { text: "Cefepime", explanation: "Incorrect. While effectively coverage, Ceftriaxone is strictly preferred/guideline based. This would be the correct answer for Pseudomonas." },
      { text: "Cephalexin", explanation: "Incorrect. Renally eliminated. This would be the correct answer for oral therapy." },
      { text: "Cefadroxil", explanation: "Incorrect. Oral agent. This would be the correct answer for skin infection." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Severe Lyme? Ceftriaxone IV.",
    pdfPage: 17,
  },
  {
    id: 27,
    category: "Carbapenems: Spectrum Gaps",
    questionText: "While Carbapenems are 'Gorillacillins' with huge susceptibility, they generally do NOT cover:",
    options: [
      { text: "Bacteroides fragilis", explanation: "Incorrect. They have excellent anaerobic coverage. This would be the correct answer for Aminoglycosides." },
      { text: "Pseudomonas (except Ertapenem)", explanation: "Incorrect. They generally cover Pseudomonas. This would be the correct answer for Ertapenem specifically." },
      { text: "MRSA", explanation: "Correct. Carbapenems do NOT cover MRSA. You need Vanco/Dapto/Linezolid/Ceftaroline for that." },
      { text: "ESBL E. coli", explanation: "Incorrect. Carbapenems are the TOC for ESBL. This would be the correct answer for Ceftriaxone." },
      { text: "MSSA", explanation: "Incorrect. They cover MSSA well. This would be the correct answer for Aztreonam." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Carbapenems don't kill MRSA. Don't waste them if MRSA is the suspect.",
    pdfPage: 15,
  },
  {
    id: 28,
    category: "Vancomycin vs Metronidazole",
    questionText: "Oral Vancomycin is preferred over Metronidazole for C. diff colitis because:",
    options: [
      { text: "It is cheaper", explanation: "Incorrect. Vancomycin PO is expensive (historically). This would be the correct answer for Metronidazole." },
      { text: "It has fewer systemic side effects", explanation: "Incorrect. Both have generally low systemic absorption/side effects when used correctly (Metro has some). This would be the correct answer if Metronidazole caused seizures." },
      { text: "Metronidazole is no longer recommended as first-line for any severity of C. diff due to lower efficacy", explanation: "Correct. Guidelines changed. Oral Vanco or Fidaxomicin are first line. Metronidazole is relegated to resource-limited settings for mild disease." },
      { text: "Metronidazole covers MRSA", explanation: "Incorrect. It does not. This would be the correct answer if MRSA colitis existed." },
      { text: "Vancomycin tastes better", explanation: "Incorrect. The oral solution is bitter. This would be the correct answer if flavor determined guidelines." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "C. diff Guidelines: Vanco PO or Fidaxomicin. RIP Metronidazole (for this use).",
    pdfPage: 32,
  },
  {
    id: 29,
    category: "Cephalosporins: Gen 1 Mnemonic",
    questionText: "The mnemonic 'PEcK' for First Generation Cephalosporins refers to their Gram-negative coverage. What does it stand for?",
    options: [
      { text: "Pseudomonas, E. coli, Klebsiella", explanation: "Incorrect. No Pseudomonas. This would be the correct answer for Cefepime." },
      { text: "Proteus, E. coli, Klebsiella", explanation: "Correct. Proteus mirabilis, E. coli, Klebsiella pneumoniae." },
      { text: "Providencia, Enterobacter, Kingella", explanation: "Incorrect. This would be the correct answer for a made-up mnemonic." },
      { text: "Peptostreptococcus, Escherichia, Kocuria", explanation: "Incorrect. This would be the correct answer for a microbiology trivia test." },
      { text: "None of the above", explanation: "Incorrect." }
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "1st Gen = PEcK. 2nd Gen = HEN PEcK (H. flu, Enterobacter/Aerogenes, Neisseria).",
    pdfPage: 42,
  },
  {
    id: 30,
    category: "Vancomycin: Pharmacology",
    questionText: "Because Vancomycin is a large glycopeptide, it is unable to penetrate the outer membrane of:",
    options: [
      { text: "Gram-positive rods", explanation: "Incorrect. Vanco covers these (Listeria/Bacillus exception partially). This would be the correct answer for organisms with intrinsic resistance." },
      { text: "Gram-positive cocci", explanation: "Incorrect. This is the main target. This would be the correct answer for Aztreonam." },
      { text: "Gram-negative bacteria", explanation: "Correct. The outer membrane porins of Gram-negatives are too small for Vanco. Hence, intrinsic resistance." },
      { text: "Anaerobes", explanation: "Incorrect. It covers G+ anaerobes like C. diff. This would be the correct answer for Aminoglycosides." },
      { text: "It penetrates everything", explanation: "Incorrect. This would be the correct answer for small lipophilic molecules." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Vancomycin is too fat for Gram-negative porins. G+ only!",
    pdfPage: 32,
  },
  {
    id: 31,
    category: "Beta-Lactamase Inhibitors",
    questionText: "Which of the following combinations represents a 'Cephalosporin + Beta-lactamase inhibitor' explicitly designed to treat MDR Pseudomonas and ESBL Enterobacteriaceae?",
    options: [
      { text: "Amoxicillin-Clavulanate", explanation: "Incorrect. Penicillin based. This would be the correct answer if asking about Augmentin." },
      { text: "Piperacillin-Tazobactam", explanation: "Incorrect. Penicillin based. This would be the correct answer if asking about Zosyn." },
      { text: "Ceftolozane-Tazobactam", explanation: "Correct. Ceftolozane is a novel cephalosporin paired with Tazobactam for MDR Gram-negatives." },
      { text: "Meropenem-Vaborbactam", explanation: "Incorrect. Carbapenem based. This would be the correct answer if asking about Vabomere." },
      { text: "Imipenem-Relebactam", explanation: "Incorrect. Carbapenem based. This would be the correct answer if asking about Recarbrio." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Ceftolozane-Tazobactam (Zerbaxa) = The 'Super Pseudomonas' drug.",
    pdfPage: 26,
  },
  {
    id: 32,
    category: "Mechanisms: Overview",
    questionText: "Which of the following drugs acts by binding to the 50S ribosomal subunit?",
    options: [
      { text: "Cefepime", explanation: "Incorrect. Cell wall (PBP). This would be the correct answer if asking about Beta-lactams." },
      { text: "Vancomycin", explanation: "Incorrect. Cell wall (D-Ala-D-Ala). This would be the correct answer if asking about Glycopeptides." },
      { text: "Doxycycline", explanation: "Incorrect. 30S ribosome. This would be the correct answer if asking about Tetracyclines." },
      { text: "Azithromycin", explanation: "Correct. Macrolides bind the 50S subunit. (Note: Reviewing mechanism overlap)." },
      { text: "Ciprofloxacin", explanation: "Incorrect. DNA Gyrase. This would be the correct answer if asking about Fluoroquinolones." },
    ],
    correctAnswerIndex: 3,
    clinicalPearl: "Beta-lactams/Vanco = Cell Wall. Aminoglycosides/Tetracyclines = 30S. Macrolides/Clinda/Linezolid = 50S. FQ = DNA.",
    pdfPage: 5,
  },
  {
    id: 33,
    category: "Synergy",
    questionText: "Historically, Enterococcal endocarditis is treated with Ampicillin + Gentamicin or Ceftriaxone. Why is the Aminoglycoside or Cephalosporin added?",
    options: [
      { text: "To cover co-infection", explanation: "Incorrect. Not the primary reason. This would be the correct answer if polymicrobial infection was suspected." },
      { text: "For synergistic killing", explanation: "Correct. With Ampicillin breaking the wall, Gentamicin can enter to kill the ribosome, or Ceftriaxone saturates complementary PBPs. " },
      { text: "To prevent renal toxicity", explanation: "Incorrect. Aminoglycosides increase renal toxicity. This would be the correct answer if asking about dose reduction." },
      { text: "To reduce cost", explanation: "Incorrect. This would be the correct answer if monotherapy was equally effective." },
      { text: "It is not added", explanation: "Incorrect. It is standard of care. This would be the correct answer if organism was VRE (sometimes)." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Enterococcal Endocarditis requires SYNERGY. It's tough to kill.",
    pdfPage: 19,
  },
  {
    id: 34,
    category: "Adverse Effects: Nephrotoxicity",
    questionText: "Concomitant use of Vancomycin and Piperacillin-Tazobactam (Zosyn) is associated with an increased risk of:",
    options: [
      { text: "Ototoxicity", explanation: "Incorrect. Primarily Vanco/Aminoglycoside issue. This would be the correct answer for Vanco + Gentamicin." },
      { text: "Acute Kidney Injury (Nephrotoxicity)", explanation: "Correct. The 'Vanco-Zosyn' combination is notorious for higher rates of AKI compared to Vanco-Cefepime." },
      { text: "Hepatotoxicity", explanation: "Incorrect. Not the main interaction risk. This would be the correct answer for alcohol + isoniazid." },
      { text: "Seizures", explanation: "Incorrect. Not the main interaction. This would be the correct answer for Imipenem." },
      { text: "Red Man Syndrome", explanation: "Incorrect. That's Vanco alone. This would be the correct answer if asking about Vanco rapid infusion." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Vanco + Zosyn = Sad Kidneys. Watch the Creatinine.",
    pdfPage: 32,
  },
  {
    id: 35,
    category: "Pharmacokinetics: Time vs Concentration",
    questionText: "Beta-lactams (like Cephalosporins) exhibit which type of killing characteristic?",
    options: [
      { text: "Concentration-dependent killing", explanation: "Incorrect. This is Aminoglycosides/Fluoroquinolones. This would be the correct answer for Gentamicin." },
      { text: "Time-dependent killing (Time > MIC)", explanation: "Correct. Efficacy depends on the TIME the drug concentration remains above the MIC." },
      { text: "Post-antibiotic effect driven", explanation: "Incorrect. This would be the correct answer for Aminoglycosides." },
      { text: "Area Under the Curve (AUC) dependent", explanation: "Incorrect. This is Vanco. This would be the correct answer for Vancomycin." },
      { text: "None", explanation: "Incorrect. This would be the correct answer if drug didn't work." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Beta-lactams need TIME. Frequent dosing or continuous infusions help.",
    pdfPage: 15,
  },
  {
    id: 36,
    category: "Resistance: ESBL",
    questionText: "An E. coli strain produces Extended-Spectrum Beta-Lactamase (ESBL). What is the drug of choice?",
    options: [
      { text: "Ceftriaxone", explanation: "Incorrect. ESBLs hydrolyze 3rd gen cephs. This would be the correct answer for non-ESBL E. coli." },
      { text: "Piperacillin-Tazobactam", explanation: "Incorrect. Often ineffective for serious ESBL infections (meropenem trial). This would be the correct answer for less serious infections (controversial)." },
      { text: "Carbapenem (e.g., Meropenem)", explanation: "Correct. Carbapenems are stable against ESBLs." },
      { text: "Cefepime", explanation: "Incorrect. Mixed efficacy, generally avoided for confirmed ESBL. This would be the correct answer for AmpC (sometimes)." },
      { text: "Vancomycin", explanation: "Incorrect. No G- activity. This would be the correct answer for MRSA." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "ESBL = Carbapenem. Don't play games.",
    pdfPage: 15,
  },
  {
    id: 37,
    category: "Daptomycin: Pulmonary",
    questionText: "A patient is treated with Daptomycin for right-sided endocarditis. They develop septic emboli to the lungs. Why must the antibiotic regimen be changed?",
    options: [
      { text: "Daptomycin makes emboli larger", explanation: "Incorrect. This would be the correct answer if drug was pro-thrombotic." },
      { text: "Daptomycin cannot treat the lung infection sequestered in the emboli due to surfactant inactivation", explanation: "Correct. Even if the source is endocarditis, if the infection spreads to the lungs, Daptomycin will fail there." },
      { text: "Daptomycin is toxic to ischemic lung tissue", explanation: "Incorrect. This would be the correct answer if drug caused necrosis." },
      { text: "It does not need to be changed", explanation: "Incorrect. It must be changed. This would be the correct answer if lungs were clear." },
      { text: "None of the above", explanation: "Incorrect." }
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Septic Emboli to lungs on Dapto? Switch. It won't work in the lungs.",
    pdfPage: 39,
  },
  {
    id: 38,
    category: "Cephalosporins: Gen 3 Names",
    questionText: "Which of the following is NOT a Third Generation Cephalosporin?",
    options: [
      { text: "Ceftriaxone", explanation: "Incorrect. It is. This would be the correct answer if asking for a 3rd gen." },
      { text: "Cefotaxime", explanation: "Incorrect. It is. This would be the correct answer if asking for a 3rd gen." },
      { text: "Cefdinir", explanation: "Incorrect. It is. This would be the correct answer if asking for a 3rd gen." },
      { text: "Cefepime", explanation: "Correct. Cefepime is Fourth generation." },
      { text: "Cefpodoxime", explanation: "Incorrect. It is. This would be the correct answer if asking for a 3rd gen." },
    ],
    correctAnswerIndex: 3,
    clinicalPearl: "Review your generations. Cefepime = 4.",
    pdfPage: 50,
  },
  {
    id: 39,
    category: "Carbapenems: Allergies",
    questionText: "A patient has a delayed rash (non-anaphylactic) to Amoxicillin. Can they receive Meropenem?",
    options: [
      { text: "No, strict contraindication", explanation: "Incorrect. Cross-reactivity is very low (<1%). This would be the correct answer for Cephalosporins (historically thought, though actually low too)." },
      { text: "Yes, the cross-reactivity is negligible and it is safe", explanation: "Correct. With a mild penicillin allergy, carbapenems are considered safe." },
      { text: "Only with desensitization", explanation: "Incorrect. Not needed for mild rash. This would be the correct answer for Anaphylaxis + strict need." },
      { text: "Only if given orally", explanation: "Incorrect. Meropenem is IV only. This would be the correct answer if Meropenem was oral." },
      { text: "Only if Aztreonam fails", explanation: "Incorrect. Preferred over Aztreonam for broad coverage. This would be the correct answer if severe allergy." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "PCN Allergy cross-reactivity with Carbapenems is <1%. Usually safe unless history of anaphylaxis is severe.",
    pdfPage: 44,
  },
  {
    id: 40,
    category: "Vancomycin: Generic Name",
    questionText: "Vancomycin belongs to which class of antibiotics?",
    options: [
      { text: "Aminoglycoside", explanation: "Incorrect. This would be the correct answer for Gentamicin." },
      { text: "Macrolide", explanation: "Incorrect. This would be the correct answer for Azithromycin." },
      { text: "Glycopeptide", explanation: "Correct." },
      { text: "Lipopeptide", explanation: "Incorrect. That is Daptomycin. This would be the correct answer for Daptomycin." },
      { text: "Beta-lactam", explanation: "Incorrect. This would be the correct answer for Penicillin." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Vancomycin is a Glycopeptide.",
    pdfPage: 3,
  },
  {
    id: 41,
    category: "Clinical Scenarios: Febrile Neutropenia",
    questionText: "A chemotherapy patient presents with febrile neutropenia. Empiric therapy MUST cover Pseudomonas. Which monotherapy is appropriate?",
    options: [
      { text: "Ceftriaxone", explanation: "Incorrect. No pseudomonas coverage. This would be the correct answer for community acquired pneumonia." },
      { text: "Ertapenem", explanation: "Incorrect. No Pseudomonas coverage. This would be the correct answer for community intra-abdominal infection." },
      { text: "Cefepime", explanation: "Correct. Cefepime covers Pseudomonas and is a standard for febrile neutropenia." },
      { text: "Vancomycin", explanation: "Incorrect. G+ only. This would be the correct answer for MRSA." },
      { text: "Metronidazole", explanation: "Incorrect. Anaerobes only. This would be the correct answer for Anaerobes." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Febrile Neutropenia = Cefepime, Meropenem, or Zosyn. Must cover Pseudomonas.",
    pdfPage: 28,
  },
  {
    id: 42,
    category: "Mechanisms: Resistance",
    questionText: "AmpC Beta-lactamases are chromosomally encoded and inducible. Exposure to 3rd generation cephalosporins can de-repress them, leading to treatment failure. Which organisms are famous for this (SPICE / HECK organisms)?",
    options: [
      { text: "Strep, Staph, Salmonella", explanation: "Incorrect. Not AmpC producers. This would be the correct answer for common pathogens." },
      { text: "Serratia, Pseudomonas, Indole+ Proteus, Citrobacter, Enterobacter", explanation: "Correct. These carry AmpC." },
      { text: "Shigella, Pasteurella, Eikenella", explanation: "Incorrect. This would be the correct answer for bite wounds (Pasteurella/Eikenella)." },
      { text: "Syphilis, Peptostreptococcus", explanation: "Incorrect. This would be the correct answer for Penicillin G spectrum." },
      { text: "None of the above", explanation: "Incorrect." }
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "AmpC organisms (SPICE)? Use Cefepime or Carbapenems. Avoid Ceftriaxone.",
    pdfPage: 15,
  },
  {
    id: 43,
    category: "Adverse Effects: Biliary",
    questionText: "Which Cephalosporin causes 'Biliary Sludge' (pseudolithiasis)?",
    options: [
      { text: "Ceftazidime", explanation: "Incorrect. Renal excretion. This would be the correct answer for Pseudomonas." },
      { text: "Cefepime", explanation: "Incorrect. Renal excretion. This would be the correct answer for Pseudomonas." },
      { text: "Ceftriaxone", explanation: "Correct. It precipitates with calcium in bile." },
      { text: "Cefuroxime", explanation: "Incorrect. This would be the correct answer for 2nd gen." },
      { text: "Cephalexin", explanation: "Incorrect." }
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Ceftriaxone = Sludge.",
    pdfPage: 19,
  },
  {
    id: 44,
    category: "Vancomycin: Enteral Absorption",
    questionText: "What is the oral bioavailability of Vancomycin?",
    options: [
      { text: "100%", explanation: "Incorrect. This would be the correct answer for Linezolid." },
      { text: "50%", explanation: "Incorrect. This would be the correct answer for variable absorption drugs." },
      { text: "< 5% (Negligible)", explanation: "Correct. It is not absorbed. That's why it treats C. diff in the gut but nothing systemic." },
      { text: "Variable", explanation: "Incorrect. It is consistently poor. This would be the correct answer for some food-dependent drugs." },
      { text: "Depends on food", explanation: "Incorrect. This would be the correct answer if food affected it." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Vanco PO stays in the gut.",
    pdfPage: 30,
  },
  {
    id: 45,
    category: "Clinical Scenarios: Osteomyelitis",
    questionText: "A patient has diabetic foot osteomyelitis growing MRSA. They require 6 weeks of therapy but have Stage 4 CKD (Creatinine Clearance < 20). Vancomycin levels are erratic. Which alternative agent covers MRSA and does not require as rigorous renal monitoring (though CPK is needed)?",
    options: [
      { text: "Ceftriaxone", explanation: "Incorrect. No MRSA coverage. This would be the correct answer for MSSA." },
      { text: "Nafcillin", explanation: "Incorrect. MSSA only. This would be the correct answer for MSSA osteomyelitis." },
      { text: "Daptomycin", explanation: "Correct. Daptomycin covers MRSA. While renally dosed (every 48h), it avoids the direct nephrotoxicity of Vancomycin." },
      { text: "Aztreonam", explanation: "Incorrect. G- only. This would be the correct answer for Pseudomonas allergy." },
      { text: "Piperacillin-Tazobactam", explanation: "Incorrect. No MRSA. This would be the correct answer for Polymicrobial non-MRSA." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Daptomycin is a great alternative for MRSA when kidneys are bad (just dose adjust).",
    pdfPage: 39,
  },
  {
    id: 46,
    category: "Cephalosporins: Oral Generation 3",
    questionText: "Select the oral 3rd generation Cephalosporin widely used for pediatric otitis media.",
    options: [
      { text: "Cefdinir", explanation: "Correct. Cefdinir (Omnicef) is a common oral 3rd gen." },
      { text: "Cefepime", explanation: "Incorrect. IV. This would be the correct answer for IV Pseudomonas." },
      { text: "Ceftriaxone", explanation: "Incorrect. IM/IV. This would be the correct answer for IM otitis media (one shot)." },
      { text: "Cephalexin", explanation: "Incorrect. 1st gen. This would be the correct answer for skin." },
      { text: "Cefazolin", explanation: "Incorrect. IV. This would be the correct answer for IV MSSA." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Cefdinir tastes like strawberries (or red sludge) and causes red stools (complexation with iron).",
    pdfPage: 17,
  },
  {
    id: 47,
    category: "Spectrum: Listeria",
    questionText: "An older adult has meningitis. Gram stain suggests Listeria monocytogenes. The regimen of Ceftriaxone + Vancomycin is insufficient because:",
    options: [
      { text: "Ceftriaxone doesn't cover Listeria", explanation: "Correct. Cephalosporins are LAME (No Listeria). Ampicillin must be added." },
      { text: "Vancomycin antagonizes Ceftriaxone", explanation: "Incorrect. They are synergistic (often used together). This would be the correct answer if they were antagonistic." },
      { text: "Listeria is viral", explanation: "Incorrect. It is bacterial. This would be the correct answer for Meningitis caused by Enterovirus." },
      { text: "Ceftriaxone doesn't cross the BBB", explanation: "Incorrect. It does. This would be the correct answer for Cefazolin." },
      { text: "Listeria is resistant to all beta-lactams", explanation: "Incorrect. Ampicillin works. This would be the correct answer for Mycoplasma." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Add Ampicillin for Listeria!",
    pdfPage: 10,
  },
  {
    id: 48,
    category: "Daptomycin side effects",
    questionText: "Daptomycin administration can rarely result in which pulmonary pathology?",
    options: [
      { text: "Pulmonary Embolism", explanation: "Incorrect. Not a side effect. This would be the correct answer for Estrogen." },
      { text: "Eosinophilic Pneumonia", explanation: "Correct. An allergic lung reaction causing infiltrates and eosinophilia." },
      { text: "Pulmonary Fibrosis", explanation: "Incorrect. (Bleomycin/Amiodarone). This would be the correct answer for Amiodarone." },
      { text: "Pulmonary Hypertension", explanation: "Incorrect. This would be the correct answer for Fen-Phen." },
      { text: "Lung Cancer", explanation: "Incorrect. This would be the correct answer for Smoking." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Daptomycin cause Eosinophilic Pneumonia. Stop drug if infiltrates + eosinophils appear.",
    pdfPage: 47,
  },
  {
    id: 49,
    category: "Microbiology: Gram Negative Outer Membrane",
    questionText: "Beta-lactams must diffuse through what structure to reach PBPs in Gram-negative bacteria?",
    options: [
      { text: "Porin channels", explanation: "Correct. Mutations in porins are a major mechanism of resistance." },
      { text: "Thick peptidoglycan", explanation: "Incorrect. That's Gram-positive. This would be the correct answer for Gram-positives." },
      { text: "Nuclear membrane", explanation: "Incorrect. Bacteria don't have nuclei. This would be the correct answer for Eukaryotes." },
      { text: "Mitochondria", explanation: "Incorrect. Bacteria are the mitochondria (evolutionarily). This would be the correct answer for Eukaryotes." },
      { text: "Flagella", explanation: "Incorrect. Motility only. This would be the correct answer if asking about movement." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Porin loss = Resistance (esp. for Carbapenems in Pseudomonas).",
    pdfPage: 23,
  },
  {
    id: 50,
    category: "Cephalosporins: Gen 5",
    questionText: "Ceftaroline is derived from a metabolite of which earlier cephalosporin?",
    options: [
      { text: "Ceftazidime", explanation: "Correct. It is structurally related to Ceftazidime (oxime side chain) but modified for PBP2a binding." },
      { text: "Cefazolin", explanation: "Incorrect. This would be the correct answer for Cephalexin (sort of)." },
      { text: "Cefoxitin", explanation: "Incorrect. This would be the correct answer for Cefotetan (sort of 2nd gen)." },
      { text: "Cefepime", explanation: "Incorrect. This is 4th gen. This would be the correct answer for itself." },
      { text: "Ceftriaxone", explanation: "Incorrect. This is 3rd gen. This would be the correct answer if asking about 3rd gen." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Ceftaroline captures the anti-gram-negative activity of Ceftazidime + MRSA activity.",
    pdfPage: 7,
  }
];
