window.L125 = [
  {
    id: 1,
    category: "Tetracyclines: Mechanism",
    questionText: "A patient with Lyme disease is treated with Doxycycline. What is the mechanism of action of this antibiotic?",
    options: [
      { text: "Binds to 50S subunit and inhibits translocation", explanation: "Incorrect. This is the mechanism of Macrolides. This would be the correct answer if asking about Azithromycin." },
      { text: "Binds to 30S subunit and blocks binding of aminoacyl-tRNA to the A-site", explanation: "Correct. Tetracyclines reversibly bind the 30S subunit, physically blocking the A-site so tRNA cannot bring new amino acids." },
      { text: "Inhibits DNA gyrase", explanation: "Incorrect. Fluoroquinolones. This would be the correct answer if asking about Ciprofloxacin." },
      { text: "Inhibits cell wall synthesis", explanation: "Incorrect. Beta-lactams. This would be the correct answer if asking about Penicillin." },
      { text: "Binds to 23S rRNA of 50S subunit", explanation: "Incorrect. This is Linezolid/Chloramphenicol. This would be the correct answer if asking about Linezolid." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Tetracyclines bind the 30S at the A-site. 'Tetra tries to block the tRNA'.",
    pdfPage: 47,
  },
  {
    id: 2,
    category: "Macrolides: Mechanism",
    questionText: "Azithromycin inhibits bacterial growth by binding to which target?",
    options: [
      { text: "30S Ribosome", explanation: "Incorrect. This would be the correct answer for Aminoglycosides/Tetracyclines." },
      { text: "50S Ribosome (23S rRNA) at the peptide exit tunnel", explanation: "Correct. Macrolides block the exit tunnel, preventing the nascent peptide chain from growing (Inhibits Translocation)." },
      { text: "DNA Polymerase", explanation: "Incorrect. This would be the correct answer for some antivirals or Rifampin." },
      { text: "Cell membrane", explanation: "Incorrect. This would be the correct answer for Daptomycin/Polymyxins." },
      { text: "Dihydrofolate reductase", explanation: "Incorrect. This would be the correct answer for Trimethoprim." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Macrolides block the Exit Tunnel on the 50S. They stop the train from leaving the station.",
    pdfPage: 11,
  },
  {
    id: 3,
    category: "Tetracyclines: Contraindications",
    questionText: "Tetracyclines were historically contraindicated in children under 8 years old. What is the primary reason for this?",
    options: [
      { text: "Severe hepatotoxicity", explanation: "Incorrect. Can occur with high doses but not the main pediatric contraindication. This would be the correct answer if high dose IV therapy caused liver failure." },
      { text: "Cartilage damage", explanation: "Incorrect. That is Fluoroquinolones. This would be the correct answer for Ciprofloxacin." },
      { text: "Deposition in calcifying tissues (Bones/Teeth) causing discoloration", explanation: "Correct. They chelate calcium and incorporate into enamel/bone, causing permanent yellow/brown staining." },
      { text: "Seizures", explanation: "Incorrect. This would be the correct answer for Carbapenems." },
      { text: "Gray Baby Syndrome", explanation: "Incorrect. That is Chloramphenicol. This would be the correct answer for Chloramphenicol." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Tetracyclines stain teeth. However, Doxycycline is now allowed for short courses (<21 days) in kids because it binds calcium less." ,
    pdfPage: 22,
  },
  {
    id: 4,
    category: "Chloramphenicol: Toxicity",
    questionText: "A premature neonate treated with Chloramphenicol develops abdominal distension, cyanosis (gray skin), and vasomotor collapse. What physiological deficiency predisposes neonates to this toxic 'Gray Baby Syndrome'?",
    options: [
      { text: "Immature renal filtration", explanation: "Incorrect. Contributing factor, but not the metabolic deficiency. This would be the correct answer for Aminoglycoside toxicity risk." },
      { text: "Immature Hepatic Glucuronosyltransferase (UGT)", explanation: "Correct. Neonates cannot glucuronidate Chloramphenicol effectively, causing toxic accumulation." },
      { text: "Lack of stomach acid", explanation: "Incorrect. This would be the correct answer for absorption issues." },
      { text: "Open blood-brain barrier", explanation: "Incorrect. This would be the correct answer for Kernicterus mechanism (partially)." },
      { text: "G6PD deficiency", explanation: "Incorrect. This would be the correct answer for Sulfonamide hemolysis." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Gray Baby Syndrome = Chloramphenicol. Due to immature liver enzymes (Glucuronidation) in babies.",
    pdfPage: 43,
  },
  {
    id: 5,
    category: "Linezolid: Adverse Effects",
    questionText: "A patient taking an SSRI (Sertraline) for depression requires Linezolid for VRE endocarditis. The physician must monitor for which drug-drug interaction?",
    options: [
      { text: "Hypertensive crisis", explanation: "Incorrect. Possible with tyramine, but Serotonin Syndrome is the interaction with SSRIs. This would be the correct answer for Tyramine foods." },
      { text: "Serotonin Syndrome", explanation: "Correct. Linezolid is a weak MAO Inhibitor. Combined with SSRIs, it can cause toxic serotonin levels (Fever, agitation, clonus)." },
      { text: "QT prolongation", explanation: "Incorrect. This would be the correct answer for Macrolides/FQs." },
      { text: "Nephrotoxicity", explanation: "Incorrect. This would be the correct answer for Aminoglycosides/Vancomycin." },
      { text: "Liver failure", explanation: "Incorrect." }
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Linezolid is an MAO Inhibitor! Watch out for Serotonin Syndrome with SSRIs.",
    pdfPage: 48,
  },
  {
    id: 6,
    category: "Clindamycin: Spectrum",
    questionText: "Clindamycin is most useful for which type of infection?",
    options: [
      { text: "Gram-negative urinary tract infection", explanation: "Incorrect. No Gram-negative activity. This would be the correct answer for FQs/TMP-SMX." },
      { text: "Anaerobic infections above the diaphragm (e.g., Aspiration Pneumonia)", explanation: "Correct. Clindamycin covers Gram-positives and Anaerobes (Bacteroides, etc.). Useful for lung abscesses." },
      { text: "Meningitis", explanation: "Incorrect. Poor CNS penetration. This would be the correct answer for Ceftriaxone." },
      { text: "Rickettsial infections", explanation: "Incorrect. This would be the correct answer for Doxycycline." },
      { text: "Pseudomonas bacteremia", explanation: "Incorrect. This would be the correct answer for Ceftazidime/Cefepime." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Clindamycin: Anaerobes 'Above the Diaphragm' (Metronidazole is for below).",
    pdfPage: 11,
  },
  {
    id: 7,
    category: "Macrolides: Erythromycin GI",
    questionText: "Patient adherence to Erythromycin is often poor due to significant gastrointestinal cramping and motility. This is because Erythromycin:",
    options: [
      { text: "Destroys all gut flora", explanation: "Incorrect. This would be the correct answer for C. diff risk (partially)." },
      { text: "Stimulates Motilin receptors", explanation: "Correct. Erythromycin acts as a Motilin receptor agonist, directly stimulating peristalsis (sometimes used therapeutically for gastroparesis)." },
      { text: "Is extremely acidic", explanation: "Incorrect. This would be the correct answer for phlebitis (sometimes)." },
      { text: "Causes pancreatitis", explanation: "Incorrect. This would be the correct answer for alcohol/gallstones." },
      { text: "Blocks serotonin receptors", explanation: "Incorrect. This would be the correct answer for Ondansetron." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Erythromycin = Motilin Agonist. It makes your gut move (nausea/cramps).",
    pdfPage: 35,
  },
  {
    id: 8,
    category: "Tetracyclines: Zoonoses",
    questionText: "Doxycycline is the drug of choice for which tick-borne disease common in the Northeast US?",
    options: [
      { text: "Malaria", explanation: "Incorrect. Malarone/Chloroquine. This would be the correct answer for prophylaxis (sometimes Doxy)." },
      { text: "Lyme Disease (Borrelia burgdorferi)", explanation: "Correct. Doxycycline is first-line for early localized and disseminated Lyme." },
      { text: "Dengue Fever", explanation: "Incorrect. Supportive care. This would be the correct answer for nothing specific." },
      { text: "West Nile Virus", explanation: "Incorrect. Supportive. This would be the correct answer for nothing specific." },
      { text: "Yellow Fever", explanation: "Incorrect. Supportive/Vaccine. This would be the correct answer for nothing specific." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Tick bite? Think Doxycycline. (Lyme, RMSF, Ehrlichiosis).",
    pdfPage: 25,
  },
  {
    id: 9,
    category: "Resistance: D-Test",
    questionText: "A D-Test is performed on a Staphylococcus aureus isolate. There is a flattening of the zone of inhibition around Clindamycin adjacent to the Erythromycin disk. This indicates:",
    options: [
      { text: "Successful synergy", explanation: "Incorrect. This would be the correct answer if the zones merged positively." },
      { text: "Inducible resistance to Clindamycin (ERM gene)", explanation: "Correct. Erythromycin induces the methylase enzyme, which then confers resistance to Clindamycin. Do NOT use Clindamycin." },
      { text: "Contamination", explanation: "Incorrect. This would be the correct answer for random colonies." },
      { text: "Constitutive resistance", explanation: "Incorrect. That would show no zone at all. This would be the correct answer for no inhibition." },
      { text: "Sensitivity to both", explanation: "Incorrect. This would be the correct answer for full circles." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Positive D-Test = Inducible Clindamycin Resistance. Don't use Clinda or it will fail.",
    pdfPage: 13,
  },
  {
    id: 10,
    category: "Tigecycline: Black Box",
    questionText: "Tigecycline is a broad-spectrum glycylcycline. However, it has a Black Box Warning for increased mortality when used for:",
    options: [
      { text: "Skin infections", explanation: "Incorrect. It is indicated (complicated). This would be the correct answer for approved use." },
      { text: "Hospital-Acquired / Ventilator-Associated Pneumonia (HAP/VAP)", explanation: "Correct. Tigecycline distributes rapidly to tissues and has low serum levels, leading to higher failure rates in bacteremic/severe pneumonias." },
      { text: "Intra-abdominal infections", explanation: "Incorrect. It is indicated. This would be the correct answer for approved use." },
      { text: "UTIs", explanation: "Incorrect. Excreted in bile mostly, low urine levels. This would be the correct answer for poor efficacy (caution)." },
      { text: "Meningitis", explanation: "Incorrect." }
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Tigecycline: 'Tiger' doesn't swim (Low serum levels). decreased efficacy in bacteremia/VAP. Increased mortality.",
    pdfPage: 29,
  },
  {
    id: 11,
    category: "Macrolides: Drug Interactions",
    questionText: "Which macrolides are potent inhibitors of CYP3A4, requiring careful medication review?",
    options: [
      { text: "Azithromycin only", explanation: "Incorrect. Azithromycin does NOT inhibit CYP3A4. This would be the correct answer for the non-inhibitor." },
      { text: "Erythromycin and Clarithromycin", explanation: "Correct. These can cause statin toxicity (rhabdomyolysis) or warfarin toxicity." },
      { text: "Fidaxomicin", explanation: "Incorrect. Minimal systemic absorption. This would be the correct answer for local gut effect." },
      { text: "All macrolides", explanation: "Incorrect. Azithro is the exception. This would be the correct answer if Azithro was included." },
      { text: "None", explanation: "Incorrect. This would be the correct answer for Penicillins." }
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Azithromycin is the 'Safe' Macrolide for interactions. Erythro/Clarithro inhibit CYP3A4.",
    pdfPage: 12,
  },
  {
    id: 12,
    category: "Chloramphenicol: Aplastic Anemia",
    questionText: "Chloramphenicol can cause two types of bone marrow suppression: dose-dependent suppression and:",
    options: [
      { text: "Idiosyncratic, irreversible aplastic anemia", explanation: "Correct. Rare, fatal, and not dose-dependent. Can happen after one eye drop." },
      { text: "Transient neutropenia", explanation: "Incorrect. This is part of the dose-dependent suppression. This would be the correct answer for reversible suppression." },
      { text: "Polycythemia vera", explanation: "Incorrect. Too many cells. This would be the correct answer for malignancy." },
      { text: "Leukemia", explanation: "Incorrect. Though aplastic anemia can predispose to it later. This would be the correct answer for malignancy." },
      { text: "Thrombocytosis", explanation: "Incorrect. High platelets. This would be the correct answer for inflammation." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Chloramphenicol causes Aplastic Anemia. It's rare but deadly/irreversible.",
    pdfPage: 14,
  },
  {
    id: 13,
    category: "Linezolid: Spectrum",
    questionText: "Linezolid (Oxazolidinone) is unique because it is bacteriostatic against Staphylococci and Enterococci but is:",
    options: [
      { text: "Bactericidal against Streptococci", explanation: "Correct. It kills Strep, but only inhibits Staph/Entero." },
      { text: "Active against Pseudomonas", explanation: "Incorrect. Gram-positives only. This would be the correct answer for Cefepime." },
      { text: "Active against Anaerobes", explanation: "Incorrect. Some, but not the unique feature. This would be the correct answer for Metronidazole." },
      { text: "Antifungal", explanation: "Incorrect. This would be the correct answer for Azoles." },
      { text: "Absorbed poorly", explanation: "Incorrect. 100% bioavailable. This would be the correct answer for Vancomycin (oral)." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Linezolid is a 'Static' drug for MRSA/VRE (stops growth), but 'Cidal' for Strep.",
    pdfPage: 16,
  },
  {
    id: 14,
    category: "Tetracyclines: Absorption",
    questionText: "Patients taking Doxycycline should be advised to avoid concomitant ingestion of:",
    options: [
      { text: "Fatty foods", explanation: "Incorrect. Food actually helps tolerability. This would be the correct answer for some other drugs." },
      { text: "Dairy, Antacids, or Iron supplements", explanation: "Correct. Divalent cations (Ca2+, Mg2+, Fe2+) chelate the drug, preventing absorption." },
      { text: "Citrus juices", explanation: "Incorrect. This would be the correct answer for some CYP interactions." },
      { text: "Leafy greens", explanation: "Incorrect. Vitamin K. This would be the correct answer for Warfarin." },
      { text: "Red meat", explanation: "Incorrect. This would be the correct answer for nothing." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Don't take Tetras with Milk or Antacids. The calcium binds the drug in the gut.",
    pdfPage: 52,
  },
  {
    id: 15,
    category: "Clindamycin: Adverse Effects",
    questionText: "Clindamycin has the highest association (historically) with which superinfection?",
    options: [
      { text: "Candida esophagitis", explanation: "Incorrect. Possible but C.diff is the classic. This would be the correct answer for fungal overgrowth." },
      { text: "Clostridioides (Clostridium) difficile colitis", explanation: "Correct. Though all antibiotics can cause it, Clindamycin is the classic offender." },
      { text: "Pseudomonas pneumonia", explanation: "Incorrect. This would be the correct answer for hospital pathogens." },
      { text: "Aspergillosis", explanation: "Incorrect. This would be the correct answer for fungi." },
      { text: "MRSA skin infection", explanation: "Incorrect. This would be the correct answer for resistant Staph." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Clindamycin = C. diff. It wipes out the gut flora effectively.",
    pdfPage: 8,
  },
  {
    id: 16,
    category: "Macrolides: Pertussis",
    questionText: "Which class of antibiotics is the treatment of choice for Pertussis (Whooping Cough) and for post-exposure prophylaxis?",
    options: [
      { text: "Penicillins", explanation: "Incorrect. Not effective. This would be the correct answer for Strep." },
      { text: "Fluoroquinolones", explanation: "Incorrect. Generally not used. This would be the correct answer for UTI/Pneumonia." },
      { text: "Macrolides (Azithromycin)", explanation: "Correct. Reduces transmission and severity if started early." },
      { text: "Aminoglycosides", explanation: "Incorrect. Parenteral. This would be the correct answer for severe Gram-negative." },
      { text: "Tetracyclines", explanation: "Incorrect." }
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Whooping Cough -> Azithromycin.",
    pdfPage: 34,
  },
  {
    id: 17,
    category: "Linezolid: Hematologic Toxicity",
    questionText: "After 2 weeks of Linezolid therapy, which hematologic parameter requires close monitoring?",
    options: [
      { text: "Platelet count (Thrombocytopenia)", explanation: "Correct. Bone marrow suppression, especially thrombocytopenia, occurs with prolonged use (>2 weeks)." },
      { text: "Prothrombin time", explanation: "Incorrect. This would be the correct answer for Warfarin." },
      { text: "Ferritin", explanation: "Incorrect. This would be the correct answer for iron overload." },
      { text: "CD4 count", explanation: "Incorrect. This would be the correct answer for HIV." },
      { text: "Eosinophils", explanation: "Incorrect. This would be the correct answer for allergy/parasites." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Long-term Linezolid? Watch the Platelets drop.",
    pdfPage: 8,
  },
  {
    id: 18,
    category: "Resistance: MLSB",
    questionText: "Methylation of the ribosomal binding site (via the erm gene) confers cross-resistance to Macrolides, Lincosamides (Clindamycin), and:",
    options: [
      { text: "Streptogramin B", explanation: "Correct. The MLSB phenotype." },
      { text: "Tetracyclines", explanation: "Incorrect. Possible alternative but Macrolides preferred. This would be the correct answer for Doxycycline." },
      { text: "Aminoglycosides", explanation: "Incorrect. Diff target. This would be the correct answer for AG resistance." },
      { text: "Linezolid", explanation: "Incorrect. Usually erm doesn't affect Linezolid (cfr gene does)." },
      { text: "Vancomycin", explanation: "Incorrect." }
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "MLSB Resistance: A methylated ribosome blocks Macrolides, Clinda, and Streptogramins.",
    pdfPage: 11,
  },
  {
    id: 19,
    category: "Demeclocycline",
    questionText: "Demeclocycline is rarely used as an antibiotic but is indicated for treatment of:",
    options: [
      { text: "Diabetes Mellitus", explanation: "Incorrect. This would be the correct answer for Metformin." },
      { text: "SIADH (Syndrome of Inappropriate ADH)", explanation: "Correct. It antagonizes ADH receptors in the kidney (causing nephrogenic diabetes insipidus as a side effect/therapeutic effect)." },
      { text: "Hypertension", explanation: "Incorrect. This would be the correct answer for ACEIs." },
      { text: "Hypercalcemia", explanation: "Incorrect. This would be the correct answer for Bisphosphonates." },
      { text: "Acne", explanation: "Incorrect. Other tetras used, but Demeclocycline is special for SIADH. This would be the correct answer for Minocycline." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Demeclocycline treats SIADH by causing deliberate Diabetes Insipidus.",
    pdfPage: 9,
  },
  {
    id: 20,
    category: "Tetracyclines: Photosensitivity",
    questionText: "A patient on Doxycycline develops a severe sunburn after a short time outside. This reaction is:",
    options: [
      { text: "Stevens-Johnson Syndrome", explanation: "Incorrect. This would be the correct answer for Sulfas/Antiepileptics." },
      { text: "Phototoxicity (Photosensitivity)", explanation: "Correct. Tetras absorb UV light and release energy, damaging skin." },
      { text: "Solar urticaria", explanation: "Incorrect. This would be the correct answer for sun allergy." },
      { text: "Lupus flare", explanation: "Incorrect. This would be the correct answer for SLE photo-exacerbation." },
      { text: "Angioedema", explanation: "Incorrect. This would be the correct answer for ACE inhibitors." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Doxycycline = Sunburn. Wear sunscreen or stay inside.",
    pdfPage: 3,
  },
  {
    id: 21,
    category: "Macrolides: QT Interval",
    questionText: "Which cardiac adverse effect is a class effect of Macrolides?",
    options: [
      { text: "Bradycardia", explanation: "Incorrect. This would be the correct answer for Beta Blockers." },
      { text: "QT Interval Prolongation", explanation: "Correct. Associated with Torsades de Pointes." },
      { text: "Heart block", explanation: "Incorrect. This would be the correct answer for CCBs." },
      { text: "Myocarditis", explanation: "Incorrect. This would be the correct answer for viruses." },
      { text: "Pericarditis", explanation: "Incorrect. This would be the correct answer for viruses." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Macrolides prolong the QT. Careful with other QT drugs (e.g., Ondansetron, Antipsychotics).",
    pdfPage: 13,
  },
  {
    id: 22,
    category: "Clinical Scenarios: Atypical Pneumonia",
    questionText: "A college student presents with a 'walking pneumonia' (Mycoplasma). Which antibiotic is first-line?",
    options: [
      { text: "Penicillin", explanation: "Incorrect. Mycoplasma has no cell wall. This would be the correct answer for Strep pneumo." },
      { text: "Cephalexin", explanation: "Incorrect. No cell wall. This would be the correct answer for skin infections." },
      { text: "Azithromycin or Doxycycline", explanation: "Correct. Both cover Atypicals (Mycoplasma/Chlamydia) by inhibiting protein synthesis." },
      { text: "Vancomycin", explanation: "Incorrect. Cell wall. This would be the correct answer for MRSA." },
      { text: "Metronidazole", explanation: "Incorrect. Anaerobes. This would be the correct answer for Aspiration." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "No cell wall? No Beta-lactams. Use Macrolides or Tetras for Mycoplasma.",
    pdfPage: 25,
  },
  {
    id: 23,
    category: "Photosensitivity: Drugs",
    questionText: "Which two classes of protein synthesis inhibitors are known for causing photosensitivity?",
    options: [
      { text: "Macrolides and Lincosamides", explanation: "Incorrect. This would be the correct answer for 50S binders." },
      { text: "Tetracyclines and Fluoroquinolones", explanation: "Incorrect. FQ is not a protein synthesis inhibitor. This would be the correct answer if asking for photosensitizing classes in general." },
      { text: "Tetracyclines", explanation: "Correct." },
      { text: "Aminoglycosides", explanation: "Incorrect. Nephro/Oto tox. This would be the correct answer for those." },
      { text: "Linezolid", explanation: "Incorrect. Myelosuppression. This would be the correct answer for that." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Tetra = Sun.",
    pdfPage: 17,
  },
  {
    id: 24,
    category: "Tetracycline: Fanconi",
    questionText: "Ingestion of expired Tetracyclines can cause:",
    options: [
      { text: "Fanconi Syndrome (Renal Tubular Acidosis type 2)", explanation: "Correct. Proximal tubule damage." },
      { text: "Liver failure", explanation: "Incorrect. This would be the correct answer for high dose Tetracyclines." },
      { text: "Blindness", explanation: "Incorrect. This would be the correct answer for Ethambutol." },
      { text: "Deafness", explanation: "Incorrect. This would be the correct answer for Aminoglycosides." },
      { text: "Seizures", explanation: "Incorrect. This would be the correct answer for Carbapenems." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Throw away old Tetracyclines. They turn toxic (Fanconi Syndrome).",
    pdfPage: 6,
  },
  {
    id: 25,
    category: "Chlamydia Treatment",
    questionText: "Uncomplicated Chlamydia trachomatis infection is treated with:",
    options: [
      { text: "Penicillin G", explanation: "Incorrect. Syphilis. This would be the correct answer for Syphilis." },
      { text: "Doxycycline (7 days) or Azithromycin (single dose)", explanation: "Correct. Though Doxy is now preferred due to Azithro efficacy concerns in some guidelines, both are classic answers." },
      { text: "Ceftriaxone", explanation: "Incorrect. Gonorrhea. This would be the correct answer for Gonorrhea." },
      { text: "Metronidazole", explanation: "Incorrect. Trichomonas. This would be the correct answer for Trichomonas." },
      { text: "Vancomycin", explanation: "Incorrect. Not effective. This would be the correct answer for MRSA." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Chlamydia = Doxy.",
    pdfPage: 26,
  },
  {
    id: 26,
    category: "Linezolid: Bioavailability",
    questionText: "What is the oral bioavailability of Linezolid?",
    options: [
      { text: "0%", explanation: "Incorrect. This would be the correct answer for Vancomycin (oral)." },
      { text: "~50%", explanation: "Incorrect. This would be the correct answer for some other drugs." },
      { text: "100%", explanation: "Correct. Excellent IV to PO conversion. Can send patients home on pills for MRSA." },
      { text: "Variable", explanation: "Incorrect. This would be the correct answer for drugs with poor absorption." },
      { text: "Requires fatty food", explanation: "Incorrect. This would be the correct answer for some antivirals." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Linezolid acts like IV even when given Oral. 100% Bioavailability.",
    pdfPage: 9,
  },
  {
    id: 27,
    category: "Chloramphenicol: Meningitis",
    questionText: "Why is Chloramphenicol a viable last-resort option for meningitis?",
    options: [
      { text: "It is bactericidal", explanation: "Incorrect. It's static. This would be the correct answer for Beta-lactams." },
      { text: "It is highly lipophilic and penetrates the BBB well", explanation: "Correct. Excellent CNS penetration." },
      { text: "It has no side effects", explanation: "Incorrect. Serious side effects exists. This would be the correct answer for placebo." },
      { text: "It is cheap", explanation: "Incorrect. This would be the correct answer for generic amoxicillin (irrelevant)." },
      { text: "It covers Pseudomonas", explanation: "Incorrect. Does not cover. This would be the correct answer for Cefepime." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Chloramphenicol gets into the brain (Lipophilic). Use only if you have to.",
    pdfPage: 14,
  },
  {
    id: 28,
    category: "Clindamycin: Vaginal Cream",
    questionText: "Patients using Clindamycin vaginal cream should be warned that:",
    options: [
      { text: "It turns urine blue", explanation: "Incorrect. This would be the correct answer for Methylene blue/Methenamine." },
      { text: "The oil base can weaken latex condoms and diaphragms", explanation: "Correct. Contraceptive failure risk." },
      { text: "It causes infertility", explanation: "Incorrect. This would be the correct answer for nothing." },
      { text: "It causes photosensitivity", explanation: "Incorrect. This would be the correct answer for Tetracyclines." },
      { text: "It must be kept frozen", explanation: "Incorrect. This would be the correct answer for some vaccines." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Clindamycin cream eats condoms. Advise safe sex precaution.",
    pdfPage: 38,
  },
  {
    id: 29,
    category: "Linezolid: Mechanism details",
    questionText: "Linezolid inhibits protein synthesis by preventing the formation of:",
    options: [
      { text: "The 70S initiation complex", explanation: "Correct. It binds the 50S and stops the 30S types of machinery from locking in." },
      { text: "Peptide bonds (transpeptidation)", explanation: "Incorrect. This would be the correct answer for Chloramphenicol/Macrolides." },
      { text: "Translocation", explanation: "Incorrect. This would be the correct answer for Macrolides." },
      { text: "Aminoacyl-tRNA binding", explanation: "Incorrect. This would be the correct answer for Tetracyclines." },
      { text: "mRNA", explanation: "Incorrect. This would be the correct answer for Rifampin (synthesis)." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Linezolid: Blocks the Initiation Complex.",
    pdfPage: 47,
  },
  {
    id: 30,
    category: "Macrolides: Half-life",
    questionText: "Which macrolide has the longest half-life (~70 hours), allowing for 5-day dosing?",
    options: [
      { text: "Erythromycin", explanation: "Incorrect. Short. This would be the correct answer for short half-life drug." },
      { text: "Clarithromycin", explanation: "Incorrect. Twice daily. This would be the correct answer for medium half-life drug." },
      { text: "Azithromycin (Z-Pak)", explanation: "Correct. Tissue sequestration leads to long t1/2." },
      { text: "Telithromycin", explanation: "Incorrect. This would be the correct answer for Ketolide." },
      { text: "Fidaxomicin", explanation: "Incorrect. Non-systemic. This would be the correct answer for C.diff." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Azithromycin lasts a long time in tissues. Z-Pak is 5 days but works for 10.",
    pdfPage: 12,
  },
  {
    id: 31,
    category: "Rocky Mountain Spotted Fever",
    questionText: "A 5-year-old child presents with fever and rash after a camping trip. RMSF is suspected. What is the treatment?",
    options: [
      { text: "Wait and see", explanation: "Incorrect. Deadly. This would be the correct answer for viral exanthem." },
      { text: "Amoxicillin", explanation: "Incorrect. Not effective for Rickettsia. This would be the correct answer for Strep throat." },
      { text: "Doxycycline", explanation: "Correct. AAP says Doxy is safe for <21 days in kids and is the ONLY good drug for RMSF. Save the life, worry about teeth later (but teeth usually fine with short course)." },
      { text: "Cephalexin", explanation: "Incorrect. This would be the correct answer for skin infections." },
      { text: "Vancomycin", explanation: "Incorrect." }
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "RMSF = Doxycycline. Even in kids. It's life or death.",
    pdfPage: 14,
  },
  {
    id: 32,
    category: "Clinical Scenarios: Abscess",
    questionText: "Why is Clindamycin often effective for lung abscesses?",
    options: [
      { text: "It penetrates abscesses well and covers anaerobes", explanation: "Correct. Aerobic/Anaerobic mix." },
      { text: "It is pH dependent", explanation: "Incorrect. This would be the correct answer for Methenamine." },
      { text: "It is bactericidal", explanation: "Incorrect. Static. This would be the correct answer for Beta-lactams." },
      { text: "It covers Gram-negatives", explanation: "Incorrect. This would be the correct answer for FQs." },
      { text: "It reduces inflammation", explanation: "Incorrect. Though some Macrolides do. This would be the correct answer for Steroids." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Lung Abscess? Clindamycin covers the anaerobic sludge.",
    pdfPage: 38,
  },
  {
    id: 33,
    category: "Linezolid: Drug Food Interaction",
    questionText: "Patients on Linezolid should avoid large amounts of Tyramine-rich foods (aged cheese, wine) to prevent:",
    options: [
      { text: "Hypotension", explanation: "Incorrect. This would be the correct answer for vasodilators." },
      { text: "Hypertensive Crisis", explanation: "Correct. Tyramine releases Norepinephrine. If MAO is inhibited by Linezolid, NE isn't broken down -> BP spike." },
      { text: "Sedation", explanation: "Incorrect. This would be the correct answer for Benzos." },
      { text: "Rash", explanation: "Incorrect. This would be the correct answer for allergy." },
      { text: "Diarrhea", explanation: "Incorrect. This would be the correct answer for general side effect." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Linezolid + Cheese/Wine = High Blood Pressure (MAOI effect).",
    pdfPage: 52,
  },
  {
    id: 34,
    category: "Resistance: Efflux",
    questionText: "TetK and TetAE genes confer resistance to Tetracyclines via which mechanism?",
    options: [
      { text: "Efflux pumps", explanation: "Correct. Pumping the drug out." },
      { text: "Ribosomal protection", explanation: "Incorrect. That's TetM. This would be the correct answer for TetM." },
      { text: "Enzymatic degradation", explanation: "Incorrect. This would be the correct answer for Beta-lactamases." },
      { text: "Target modification", explanation: "Incorrect. This would be the correct answer for Methylation (MLSB)." },
      { text: "Decreased uptake", explanation: "Incorrect. This would be the correct answer for Porin loss." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "TetK = Efflux. Pumping it out.",
    pdfPage: 7,
  },
  {
    id: 35,
    category: "Ribosomal Protection Proteins",
    questionText: "TetM protein confers resistance by:",
    options: [
      { text: "Binding to the ribosome and preventing Tetracycline binding", explanation: "Correct. Ribosomal Protection." },
      { text: "Pumping drug out", explanation: "Incorrect. This would be the correct answer for Efflux (TetK)." },
      { text: "Destroying the drug", explanation: "Incorrect. This would be the correct answer for Enzymatic degradation." },
      { text: "Methylating the drug", explanation: "Incorrect. Often target is methylated. This would be the correct answer for modification." },
      { text: "Changing the cell wall", explanation: "Incorrect. This would be the correct answer for Vancomycin resistance." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "TetM = Bodyguard for the Ribosome.",
    pdfPage: 24,
  },
  {
    id: 36,
    category: "Macrolides: Pharmacokinetics",
    questionText: "Do Macrolides penetrate the CSF?",
    options: [
      { text: "Yes, excellent", explanation: "Incorrect. This would be the correct answer for Chloramphenicol." },
      { text: "No, poor penetration", explanation: "Correct. Not for meningitis." },
      { text: "Only Azithromycin", explanation: "Incorrect. This would be the correct answer for nothing." },
      { text: "Only in neonates", explanation: "Incorrect. This would be the correct answer for nothing." },
      { text: "Only with alcohol", explanation: "Incorrect. This would be the correct answer for nothing." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Macrolides don't cross the BBB.",
    pdfPage: 11,
  },
  {
    id: 37,
    category: "Syphilis Alternative",
    questionText: "A patient with Syphilis and a severe Penicillin allergy (anaphylaxis) can be treated with:",
    options: [
      { text: "Doxycycline", explanation: "Correct. Doxy is the alternative for Syphilis (though inferior to PCN, requires long course)." },
      { text: "Metronidazole", explanation: "Incorrect. This would be the correct answer for bacteria/protozoa." },
      { text: "Vancomycin", explanation: "Incorrect. Cell wall/MRSA. This would be the correct answer for MRSA." },
      { text: "Gentamicin", explanation: "Incorrect. This would be the correct answer for Gram-negative sepsis." },
      { text: "Linezolid", explanation: "Incorrect. This would be the correct answer for VRE." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Syphilis + PCN Allergy? -> Doxycycline (14-28 days).",
    pdfPage: 26,
  },
  {
    id: 38,
    category: "Tetracyclines: Minocycline",
    questionText: "Minocycline is frequently used for:",
    options: [
      { text: "Acne Vulgaris", explanation: "Correct. Lipid soluble, penetrates skin follicles." },
      { text: "Meningitis", explanation: "Incorrect. Large molecule. This would be the correct answer for poor penetration." },
      { text: "Endocarditis", explanation: "Incorrect. This would be the correct answer for bacteremia." },
      { text: "Sepsis", explanation: "Incorrect. This would be the correct answer for broad spectrum coverage." },
      { text: "TB", explanation: "Incorrect. This would be the correct answer for RIPE therapy." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Minocycline = Acne. (Can cause blue skin discoloration side effect).",
    pdfPage: 9,
  },
  {
    id: 39,
    category: "Clinical Scenarios: MRSA",
    questionText: "Which oral antibiotic covers Community-Acquired MRSA?",
    options: [
      { text: "Cephalexin", explanation: "Incorrect. This would be the correct answer for MSSA." },
      { text: "Amoxicillin", explanation: "Incorrect. This would be the correct answer for Strep." },
      { text: "Doxycycline or Clindamycin or Trimethoprim-Sulfamethoxazole", explanation: "Correct. All three are classic oral options for CA-MRSA." },
      { text: "Azithromycin", explanation: "Incorrect. Resistance is high. This would be the correct answer for Atypicals." },
      { text: "Ciprofloxacin", explanation: "Incorrect. Resistance high. This would be the correct answer for Gram-negatives." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Oral MRSA drugs: Doxy, Clinda, Bactrim.",
    pdfPage: 26,
  },
  {
    id: 40,
    category: "Tetracyclines: Pregnancy",
    questionText: "Tetracyclines use in the 2nd/3rd trimester is associated with:",
    options: [
      { text: "Fetal bone growth retardation and teeth discoloration", explanation: "Correct." },
      { text: "Neural tube defects", explanation: "Incorrect. This would be the correct answer for Folate deficiency." },
      { text: "Kernicterus", explanation: "Incorrect. This would be the correct answer for Sulfas/Ceftriaxone." },
      { text: "Hearing loss", explanation: "Incorrect. This would be the correct answer for Aminoglycosides." },
      { text: "Macrosomia", explanation: "Incorrect. This would be the correct answer for Diabetes." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Tetras love Calcium. Stay away from growing fetus bones/teeth.",
    pdfPage: 8,
  },
  {
    id: 41,
    category: "Chloramphenicol: Mitochondrial toxicity",
    questionText: "Chloramphenicol toxicity (bone marrow) is likely due to inhibition of:",
    options: [
      { text: "Mammalian mitochondrial ribosomes", explanation: "Correct. Mitochondria have 70S-like ribosomes (endosymbiosis theory)." },
      { text: "Cytoplasmic ribosomes", explanation: "Incorrect. This would be the correct answer for bacterial inhibition (target)." },
      { text: "DNA polymerase", explanation: "Incorrect. This would be the correct answer for replication inhibition." },
      { text: "RNA polymerase", explanation: "Incorrect. This would be the correct answer for Rifampin." },
      { text: "Cell membrane", explanation: "Incorrect. This would be the correct answer for Daptomycin." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Mitochondria look like bacteria. Chloramphenicol suppresses them -> Bone Marrow suppression.",
    pdfPage: 42,
  },
  {
    id: 42,
    category: "Macrolides: Metabolism",
    questionText: "Erythromycin is metabolized by:",
    options: [
      { text: "Renal excretion unchanged", explanation: "Incorrect. This would be the correct answer for Aminoglycosides." },
      { text: "Hepatic CYP450 system", explanation: "Correct. Hence the interactions." },
      { text: "Lung esterases", explanation: "Incorrect. This would be the correct answer for nothing specific." },
      { text: "Plasma cholinesterases", explanation: "Incorrect. This would be the correct answer for some neuromuscular blockers." },
      { text: "Spontaneous degradation", explanation: "Incorrect. This would be the correct answer for Atracurium." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Erythro/Clarithro interact with everything via the Liver.",
    pdfPage: 35,
  },
  {
    id: 43,
    category: "Lincosamides vs Macrolides",
    questionText: "Clindamycin and Erythromycin should not be used together because:",
    options: [
      { text: "They precipitate in IV lines", explanation: "Incorrect. This would be the correct answer for physical incompatibility." },
      { text: "They compete for the same ribosomal binding site (Antagonism)", explanation: "Correct. 50S site overlap." },
      { text: "They cause additive nephrotoxicity", explanation: "Incorrect. This would be the correct answer for Vanco + AG." },
      { text: "They cause anaphylaxis", explanation: "Incorrect. This would be the correct answer for allergy." },
      { text: "One inactivates the other chemically", explanation: "Incorrect. This would be the correct answer for Beta-lactam/Aminoglycoside mixing." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Don't stack Clinda and Macrolides. They fight for the same chair.",
    pdfPage: 52,
  },
  {
    id: 44,
    category: "Clinda vs MRSA",
    questionText: "Is Clindamycin effective against CA-MRSA?",
    options: [
      { text: "Yes, often", explanation: "Correct. But check D-test." },
      { text: "No, never", explanation: "Incorrect. This would be the correct answer for Beta-lactams." },
      { text: "Only IV", explanation: "Incorrect. This would be the correct answer for Vancomycin." },
      { text: "Only with Gentamicin", explanation: "Incorrect. This would be the correct answer for Enterococcus endocarditis." },
      { text: "Only in urine", explanation: "Incorrect. This would be the correct answer for Nitrofurantoin." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Clinda works for MRSA unless the D-test is positive.",
    pdfPage: 39,
  },
  {
    id: 45,
    category: "Macrolides: Pneumonia",
    questionText: "Community Acquired Pneumonia guidelines often recommend Azithromycin monotherapy or combination therapy because it covers:",
    options: [
      { text: "MRSA", explanation: "Incorrect. This would be the correct answer for Vancomycin." },
      { text: "Atypical pathogens (Legionella, Mycoplasma, Chlamydia)", explanation: "Correct. 'Coverage of Atypicals' is the key reason for Macrolides in CAP." },
      { text: "Pseudomonas", explanation: "Incorrect. This would be the correct answer for Cefepime." },
      { text: "Anaerobes", explanation: "Incorrect. This would be the correct answer for Metronidazole." },
      { text: "VRE", explanation: "Incorrect. This would be the correct answer for Linezolid." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "CAP needs Atypical coverage. Azithro hits the 'walking pneumonia' bugs.",
    pdfPage: 25,
  },
  {
    id: 46,
    category: "Tetracycline: Excretion",
    questionText: "Which Tetracycline is safe in renal failure because it is eliminated via feces?",
    options: [
      { text: "Tetracycline", explanation: "Incorrect. Renal. This would be the correct answer for Tetracycline." },
      { text: "Doxycycline", explanation: "Correct. 'Doxy is excreted in the Doody'." },
      { text: "Minocycline", explanation: "Incorrect. Hepatic. This would be the correct answer for Minocycline." },
      { text: "Demeclocycline", explanation: "Incorrect. Renal. This would be the correct answer for Demeclocycline." },
      { text: "None", explanation: "Incorrect. This would be the correct answer for nothing." }
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Doxy is safe for failing kidneys.",
    pdfPage: 8,
  },
  {
    id: 47,
    category: "Spectrum: VRE",
    questionText: "Vancomycin Resistant Enterococcus (VRE) can be treated with:",
    options: [
      { text: "Cephalexin", explanation: "Incorrect. This would be the correct answer for MSSA." },
      { text: "Linezolid", explanation: "Correct. Linezolid is the anti-VRE drug." },
      { text: "Azithromycin", explanation: "Incorrect. This would be the correct answer for Atypicals." },
      { text: "Clindamycin", explanation: "Incorrect. This would be the correct answer for Anaerobes." },
      { text: "Metronidazole", explanation: "Incorrect. This would be the correct answer for Anaerobes." }
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "VRE? Use Linezolid (or Daptomycin).",
    pdfPage: 16,
  },
  {
    id: 48,
    category: "Macrolides: Static or Cidal",
    questionText: "Protein synthesis inhibitors like Macrolides and Tetracyclines are generally considered:",
    options: [
      { text: "Bactericidal", explanation: "Incorrect. (Aminoglycosides are the exception). This would be the correct answer for Beta-lactams." },
      { text: "Bacteriostatic", explanation: "Correct. They stop growth, letting the immune system finish the job." },
      { text: "Fungicidal", explanation: "Incorrect. This would be the correct answer for Amphotericin." },
      { text: "Virucidal", explanation: "Incorrect. This would be the correct answer for Acyclovir." },
      { text: "Ineffective", explanation: "Incorrect. This would be the correct answer for nothing." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Protein Synthesis Inhibitors are STATIC (Stop growth). Except Aminoglycosides (CIDAL).",
    pdfPage: 5,
  },
  {
    id: 49,
    category: "Azithromycin: STDs",
    questionText: "Is Azithromycin safe in pregnancy for Chlamydia treatment?",
    options: [
      { text: "Yes", explanation: "Correct. Class B." },
      { text: "No, teratogenic", explanation: "Incorrect. This would be the correct answer for Tetracyclines." },
      { text: "Only in 3rd trimester", explanation: "Incorrect. This would be the correct answer for Sulfas (sometimes)." },
      { text: "Only IV", explanation: "Incorrect. This would be the correct answer for serious infections." },
      { text: "Only with probenecid", explanation: "Incorrect. This would be the correct answer for Penicillin (to boost levels)." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Azithro is safe for pregnant moms.",
    pdfPage: 48,
  },
  {
    id: 50,
    category: "Summary: Targets",
    questionText: "Which drug binds the 30S subunit? (Select the only 30S binder in this list)",
    options: [
      { text: "Erythromycin", explanation: "Incorrect. 50S. This would be the correct answer for 50S." },
      { text: "Clindamycin", explanation: "Incorrect. 50S. This would be the correct answer for 50S." },
      { text: "Chloramphenicol", explanation: "Incorrect. 50S. This would be the correct answer for 50S." },
      { text: "Linezolid", explanation: "Incorrect. 50S. This would be the correct answer for 50S." },
      { text: "Doxycycline", explanation: "Correct. Tetracyclines = 30S." }
    ],
    correctAnswerIndex: 4,
    clinicalPearl: "Buy AT 30, CCEL at 50. (Aminoglyc, Tetra = 30S). (Chloramph, Clinda, Erythro, Linezolid = 50S).",
    pdfPage: 16,
  }
];
