window.L124 = [
  {
    id: 1,
    category: "Aminoglycosides: Mechanism",
    questionText: "A researcher investigating the mechanism of action of Gentamicin observes that it binds irreversibly to the bacterial ribosome. Which specific subunit and effect are primarily responsible for its bactericidal activity?",
    options: [
      { text: "50S subunit; inhibiting peptide bond formation", explanation: "Incorrect. This describes Macrolides/Chloramphenicol. This would be the correct answer if asking about Chloramphenicol." },
      { text: "30S subunit; preventing tRNA binding", explanation: "Incorrect. Tetracyclines bind the 30S and block tRNA binding (reversible). This would be the correct answer if asking about Tetracyclines." },
      { text: "30S subunit; causing misreading of mRNA and blocking initiation", explanation: "Correct. Aminoglycosides bind the 16S rRNA of the 30S subunit, causing misreading of the genetic code and inhibiting the initiation complex." },
      { text: "50S subunit; blocking the exit tunnel", explanation: "Incorrect. Macrolides. This would be the correct answer if asking about Erythromycin." },
      { text: "DNA gyrase; inhibiting supercoiling", explanation: "Incorrect. Fluoroquinolones. This would be the correct answer if asking about Ciprofloxacin." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Aminoglycosides are bactericidal because they bind IRREVERSIBLY to the 30S subunit, causing production of toxic, junk proteins.",
    pdfPage: 9,
  },
  {
    id: 2,
    category: "Aminoglycosides: Pharmacokinetics",
    questionText: "A patient with cystic fibrosis requires Tobramycin therapy. Why is oral administration effective only for gut decontamination and not for systemic or pulmonary infections in this context?",
    options: [
      { text: "It is rapidly metabolized by the liver", explanation: "Incorrect. It is cleared renally (systemically). This would be the correct answer for high first-pass effect drugs." },
      { text: "It is highly polar and not absorbed from the GI tract", explanation: "Correct. Aminoglycosides are polycations (highly polar) and have <1% oral bioavailability." },
      { text: "It causes severe vomiting significantly reducing absorption", explanation: "Incorrect. Nausea occurs but is not the reason for poor bioavailability. This would be the correct answer if vomiting precluded oral intake." },
      { text: "It is degraded by stomach acid", explanation: "Incorrect. It is relatively stable. This would be the correct answer for Penicillin G." },
      { text: "It binds to calcium in the gut", explanation: "Incorrect. This is Tetracyclines. This would be the correct answer for Doxycycline." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Aminoglycosides are too polar to cross membranes. IV/IM for systemic use, Inhaled for lungs, Oral only for gut effects (e.g., Neomycin).",
    pdfPage: 24,
  },
  {
    id: 3,
    category: "Aminoglycosides: Toxicity",
    questionText: "A 65-year-old male on Gentamicin for pyelonephritis reports new-onset difficulty hearing high-pitched sounds and a sensation of room spinning. Damage to which structure explains these symptoms?",
    options: [
      { text: "Optic nerve", explanation: "Incorrect. Streptomycin can cause scotomas, but this is auditory/vestibular. This would be the correct answer for Ethambutol." },
      { text: "Tympanic membrane", explanation: "Incorrect. AGs do not damage the eardrum. This would be the correct answer for otitis media rupture." },
      { text: "Hair cells in the cochlea and vestibular apparatus", explanation: "Correct. Aminoglycosides accumulate in the endolymph/perilymph, destroying hair cells (Ototoxicity). This is often irreversible." },
      { text: "Ossicles", explanation: "Incorrect. This would be the correct answer for Otosclerosis." },
      { text: "Eustachian tube", explanation: "Incorrect. This would be the correct answer for Dysfunction." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Ototoxicity from Aminoglycosides affects both Cochlear (hearing loss) and Vestibular (balance) function. It causes hair cell death.",
    pdfPage: 12,
  },
  {
    id: 4,
    category: "Aminoglycosides: Synergism",
    questionText: "Ampicillin and Gentamicin are used together for the treatment of *Enterococcus faecalis* endocarditis. What is the mechanism of this synergy?",
    options: [
      { text: "Gentamicin prevents the renal excretion of Ampicillin", explanation: "Incorrect. Probenecid does this. This would be the correct answer for Probenecid." },
      { text: "Ampicillin breaks down the cell wall, allowing Gentamicin entry", explanation: "Correct. Enterococci have thick cell walls that exclude AGs. Beta-lactams damage the wall, facilitating AG update." },
      { text: "Gentamicin inhibits beta-lactamase", explanation: "Incorrect. It does not. This would be the correct answer for Clavulanic acid." },
      { text: "They bind to the same ribosomal subunit", explanation: "Incorrect. Ampicillin binds PBP. This would be the correct answer for Macrolides + Clindamycin (antagonism)." },
      { text: "Ampicillin increases the pH of the cytoplasm", explanation: "Incorrect. This would be the correct answer if pH change was the mechanism." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Synergy in Endocarditis: The Beta-lactam opens the door (cell wall), the Aminoglycoside walks in and kills the ribosome.",
    pdfPage: 23,
  },
  {
    id: 5,
    category: "Aminoglycosides: Resistance",
    questionText: "A strain of *Klebsiella pneumoniae* is resistant to Gentamicin. The most common mechanism of acquired resistance involves:",
    options: [
      { text: "Efflux pumps", explanation: "Incorrect. Possible, but not the most common. This would be the correct answer for Tetracyclines." },
      { text: "Target modification (methylation of binding site)", explanation: "Incorrect. Less common for AGs, more for Macrolides. This would be the correct answer for Macrolides." },
      { text: "Enzymatic modification (Transferases)", explanation: "Correct. Bacteria produce Acetyl-, Phosphoryl-, or Adenyl-transferases that modify the drug so it cannot bind the ribosome." },
      { text: "Porin loss", explanation: "Incorrect. This confers resistance but enzymatic modification is predominant. This would be the correct answer for Carbapenems." },
      { text: "Thickened peptidoglycan", explanation: "Incorrect. This would be the correct answer for VISA." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Aminoglycoside Resistance = TRANSFERASES. The bacteria tag the drug with a chemical group so it won't fit the target.",
    pdfPage: 32,
  },
  {
    id: 6,
    category: "Aminoglycosides: Transport",
    questionText: "Why are Aminoglycosides ineffective against *Bacteroides fragilis* and other anaerobes?",
    options: [
      { text: "Anaerobes lack ribosomes", explanation: "Incorrect. All bacteria have ribosomes. This would be the correct answer if they were viruses." },
      { text: "Anaerobes produce specific beta-lactamases", explanation: "Incorrect. AGs are not beta-lactams. This would be the correct answer for Penicillin resistance." },
      { text: "Aminoglycoside uptake requires an oxygen-dependent pump", explanation: "Correct. Entry into the bacterial cytoplasm is an energy-dependent process requiring Oxygen. Anaerobes lack this." },
      { text: "The pH of anaerobic abscesses is too high", explanation: "Incorrect. It is usually too low, which also hinders AGs, but the lack of O2 pump is the primary intrinsic resistance factor. This would be the correct answer if pH was alkaline." },
      { text: "Anaerobes possess impermeable outer membranes", explanation: "Incorrect. Bacteroides does have an OM but the transport issue is key. This would be the correct answer for Vancomycin vs Gram-negatives." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Aminoglycosides need OXYGEN to enter the cell. They fail against Anaerobes (and in abscesses).",
    pdfPage: 9,
  },
  {
    id: 7,
    category: "Aminoglycosides: Contraindications",
    questionText: "A patient with Myasthenia Gravis is hospitalized for a serious Gram-negative infection. Aminoglycosides should be avoided if possible because they can:",
    options: [
      { text: "Induce a cholinergic crisis", explanation: "Incorrect. It blocks cholinergic transmission. This would be the correct answer for Organophosphates." },
      { text: "Block neuromuscular transmission pre-synaptically", explanation: "Correct. AGs block calcium channels at the pre-synaptic nerve terminal, inhibiting Acetylcholine release, which can cause respiratory paralysis in MG patients." },
      { text: "Directly damage muscle fibers", explanation: "Incorrect. That's Daptomycin/Statins. This would be the correct answer for Rhabdomyolysis agents." },
      { text: "Lower the seizure threshold", explanation: "Incorrect. That's Carbapenems/Fluoroquinolones. This would be the correct answer for Imipenem." },
      { text: "Cause autoimmune hemolysis", explanation: "Incorrect. This would be the correct answer for Methyldopa/Cephalosporins." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Aminoglycosides cause Neuromuscular Blockade. Absolute caution in Myasthenia Gravis (can cause respiratory failure).",
    pdfPage: 33,
  },
  {
    id: 8,
    category: "Aminoglycosides: Dosing",
    questionText: "Aminoglycosides demonstrate 'Concentration-Dependent Killing'. This pharmacodynamic property supports which dosing strategy?",
    options: [
      { text: "Continuous low-dose infusion", explanation: "Incorrect. This maximizes Time > MIC ( Beta-lactams). This would be the correct answer for Beta-lactams." },
      { text: "Once-daily (Extended Interval) dosing", explanation: "Correct. Giving a huge dose once daily maximizes the Peak/MIC ratio (killing) and allows a 'washout' period to reduce toxicity." },
      { text: "Frequent small doses (every 6 hours)", explanation: "Incorrect. This increases toxicity risk without adding efficacy. This would be the correct answer for Time-dependent drugs with short half-lives." },
      { text: "Oral administration", explanation: "Incorrect. Not absorbed. This would be the correct answer for gut decontamination." },
      { text: "Loading doses followed by low maintenance", explanation: "Incorrect. High dose extended interval is preferred. This would be the correct answer for drugs with long half-lives like Amiodarone." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "High Peak = Dead Bugs. Low Trough = Happy Kidneys. Use Once-Daily Dosing.",
    pdfPage: 8,
  },
  {
    id: 9,
    category: "Aminoglycosides: Spectrum",
    questionText: "Which Aminoglycoside is generally preferred for *Pseudomonas aeruginosa* infections due to slightly superior intrinsic activity?",
    options: [
      { text: "Gentamicin", explanation: "Incorrect. Good for Serratia/E. coli, less potent for Pseudomonas. This would be the correct answer for Enterococcal synergy." },
      { text: "Streptomycin", explanation: "Incorrect. TB/Zoonoses. This would be the correct answer for Tularemia." },
      { text: "Tobramycin", explanation: "Correct. Tobramycin is slightly more active against Pseudomonas than Gentamicin." },
      { text: "Neomycin", explanation: "Incorrect. Too toxic for systemic use. This would be the correct answer for bowel prep." },
      { text: "Kanamycin", explanation: "Incorrect. Rarely used. This would be the correct answer if other options failed." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Tobramycin > Gentamicin for Pseudomonas. (Think 'T' for 'Totally Pseudomonas').",
    pdfPage: 24,
  },
  {
    id: 10,
    category: "Aminoglycosides: Zoonoses",
    questionText: "Streptomycin is the drug of choice (or primary alternative) for which zoonotic infections?",
    options: [
      { text: "Lyme disease and Babesiosis", explanation: "Incorrect. This would be the correct answer for Doxycycline/Atovaquone." },
      { text: "Tularemia (Francisella) and Plague (Yersinia)", explanation: "Correct. Streptomycin is the classic treatment for these serious zoonoses." },
      { text: "Cat scratch disease and Bartonella", explanation: "Incorrect. This would be the correct answer for Azithromycin." },
      { text: "Q fever and Psittacosis", explanation: "Incorrect. This would be the correct answer for Doxycycline." },
      { text: "Anthrax and Listeria", explanation: "Incorrect. This would be the correct answer for Ciprofloxacin/Ampicillin." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Streptomycin is for the 'Old World' diseases: TB, Plague, and Tularemia.",
    pdfPage: 11,
  },
  {
    id: 11,
    category: "Aminoglycosides: Nephrotoxicity",
    questionText: "Aminoglycoside-induced nephrotoxicity typically manifests as:",
    options: [
      { text: "Chronic interstitial nephritis", explanation: "Incorrect. This would be the correct answer for NSAIDs/Lithium." },
      { text: "Glomerulonephritis", explanation: "Incorrect. This would be the correct answer for autoimmune diseases." },
      { text: "Acute Tubular Necrosis (ATN)", explanation: "Correct. AGs accumulate in proximal tubule cells, causing ATN. It is typically non-oliguric and reversible." },
      { text: "Post-renal obstruction", explanation: "Incorrect. This would be the correct answer for Kidney Stones." },
      { text: "Renal artery stenosis", explanation: "Incorrect. This would be the correct answer for ACE inhibitors (worsening)." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "AGs cause ATN. Monitor Creatinine. It usually recovers after stopping the drug.",
    pdfPage: 12,
  },
  {
    id: 12,
    category: "Aminoglycosides: Post-Antibiotic Effect",
    questionText: "Even when serum levels of Gentamicin drop below the MIC, bacterial growth remains suppressed for hours. This phenomenon is called:",
    options: [
      { text: "Tachyphylaxis", explanation: "Incorrect. This is rapid tolerance. This would be the correct answer for Nitrates." },
      { text: "Post-Antibiotic Effect (PAE)", explanation: "Correct. AGs have a long PAE, which allows for extended interval dosing despite a short half-life." },
      { text: "Synergy", explanation: "Incorrect. This is combined effect. This would be the correct answer for Amp + Gent." },
      { text: "Tolerance", explanation: "Incorrect. This is reduced effect. This would be the correct answer for Opioids." },
      { text: "Bioaccumulation", explanation: "Incorrect. This is buildup in tissue. This would be the correct answer for DDT." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Post-Antibiotic Effect means the bugs stay stunned even when drug levels are low. Allows Q24H dosing.",
    pdfPage: 8,
  },
  {
    id: 13,
    category: "Aminoglycosides: MDR Agents",
    questionText: "Which Aminoglycoside is resistant to many bacterial transferase enzymes and is reserved for multi-drug resistant Gram-negative infections?",
    options: [
      { text: "Gentamicin", explanation: "Incorrect. Susceptible to many enzymes. This would be the correct answer for empiric sepsis (with restrictions)." },
      { text: "Amikacin", explanation: "Correct. Amikacin has a bulky side chain that protects it from enzymatic inactivation." },
      { text: "Streptomycin", explanation: "Incorrect. High resistance. This would be the correct answer for TB." },
      { text: "Neomycin", explanation: "Incorrect. Too toxic. This would be the correct answer for topical use." },
      { text: "Paromomycin", explanation: "Incorrect. This would be the correct answer for Parasites." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Amikacin is the 'Big Gun' Aminoglycoside. Use it when Gentamicin/Tobramycin fail.",
    pdfPage: 11,
  },
  {
    id: 14,
    category: "Aminoglycosides: Tuberculosis",
    questionText: "Which Aminoglycoside is a first-line agent (historically) or second-line agent (currently) for Tuberculosis treatment?",
    options: [
      { text: "Gentamicin", explanation: "Incorrect. Not effective for TB. This would be the correct answer for Gram-negatives." },
      { text: "Streptomycin", explanation: "Correct. Streptomycin was the first cure for TB and is still used for resistant cases." },
      { text: "Tobramycin", explanation: "Incorrect. Not for TB. This would be the correct answer for Pseudomonas." },
      { text: "Neomycin", explanation: "Incorrect. Not for systemic TB. This would be the correct answer for bowel prep." },
      { text: "Plazomycin", explanation: "Incorrect. For cUTI. This would be the correct answer for MDR Enterobacteriaceae." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Streptomycin targets TB. (Mechanism: 30S).",
    pdfPage: 32,
  },
  {
    id: 15,
    category: "Aminoglycosides: Neomycin",
    questionText: "Neomycin is too nephrotoxic for parenteral use. Its primary indicated uses include topical application and:",
    options: [
      { text: "Inhalation for Cystic Fibrosis", explanation: "Incorrect. That's Tobramycin. This would be the correct answer for Tobramycin." },
      { text: "Oral administration for hepatic encephalopathy", explanation: "Correct. It reduces ammonia-producing gut bacteria." },
      { text: "IV for meningitis", explanation: "Incorrect. Too toxic. This would be the correct answer for Ceftriaxone." },
      { text: "IM for gonorrhea", explanation: "Incorrect. This would be the correct answer for Ceftriaxone." },
      { text: "Subcutaneous for abscesses", explanation: "Incorrect. Not used. This would be the correct answer for Insulin." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Neomycin: Topical (Neosporin) or Oral (Bowel Prep/Hepatic Encephalopathy). NEVER IV.",
    pdfPage: 11,
  },
  {
    id: 16,
    category: "Aminoglycosides: Pregnancy",
    questionText: "Why are Aminoglycosides generally contraindicated in pregnancy (Category D)?",
    options: [
      { text: "They cause kernicterus", explanation: "Incorrect. Sulfas/Ceftriaxone. This would be the correct answer for Ceftriaxone in neonates." },
      { text: "They cause fetal deafness (Ototoxicity)", explanation: "Correct. They cross the placenta and can destroy fetal hair cells." },
      { text: "They cause grey baby syndrome", explanation: "Incorrect. Chloramphenicol. This would be the correct answer for Chloramphenicol." },
      { text: "They cause bone deformities", explanation: "Incorrect. Tetracyclines/FQs. This would be the correct answer for Tetracyclines." },
      { text: "They cause neural tube defects", explanation: "Incorrect. Folate antagonists. This would be the correct answer for Valproate/Trimethoprim." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "AGs in pregnancy = Fetal Deafness. Avoid.",
    pdfPage: 30,
  },
  {
    id: 17,
    category: "Aminoglycosides: Chemical Structure",
    questionText: "The chemical structure of Aminoglycosides (amino sugars + glycosidic bonds) renders them:",
    options: [
      { text: "Highly lipophilic", explanation: "Incorrect. This would be the correct answer for Macrolides." },
      { text: "Highly hydrophilic (Polar)", explanation: "Correct. This limits their volume of distribution to extracellular fluid." },
      { text: "Unstable in solution", explanation: "Incorrect. They are stable. This would be the correct answer for some Penicillins." },
      { text: "Able to cross the BBB easily", explanation: "Incorrect. They are polar. This would be the correct answer for Chloramphenicol/Metronidazole." },
      { text: "Metabolized extensively by CYP450", explanation: "Incorrect. Renal excretion unchanged. This would be the correct answer for Macrolides." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "AGs are Polar Bears (Water loving). They stay in the blood/urine, don't enter fat or cells easily.",
    pdfPage: 8,
  },
  {
    id: 18,
    category: "Plazomycin",
    questionText: "Plazomycin is a next-generation aminoglycoside FDA approved for:",
    options: [
      { text: "Community-acquired pneumonia", explanation: "Incorrect. This would be the correct answer for Macrolides." },
      { text: "Complicated Urinary Tract Infections (cUTI)", explanation: "Correct. It targets MDR Enterobacteriaceae (CRE/ESBL) in the urinary tract." },
      { text: "Skin and soft tissue infections", explanation: "Incorrect. This would be the correct answer for Vancomycin (MRSA)." },
      { text: "Meningitis", explanation: "Incorrect. This would be the correct answer for Ceftriaxone." },
      { text: "Gonorrhea", explanation: "Incorrect. This would be the correct answer for Ceftriaxone." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Plazomycin = The AG for Complicated UTIs when nothing else works.",
    pdfPage: 3,
  },
  {
    id: 19,
    category: "Aminoglycosides: Monitoring",
    questionText: "To assess for accumulation and risk of toxicity in traditional dosing, when should serum levels be drawn?",
    options: [
      { text: "Peak (30 mins after dose)", explanation: "Incorrect. Trough is more predictive of toxicity. This would be the correct answer for efficacy monitoring (traditional)." },
      { text: "Trough (Right before next dose)", explanation: "Correct. An elevated trough indicates the drug isn't clearing, increasing toxicity risk." },
      { text: "Mid-interval", explanation: "Incorrect. This would be the correct answer for Nominogram plotting (Hartford)." },
      { text: "Random level", explanation: "Incorrect. This would be the correct answer for Vancomycin initial check (sometimes)." },
      { text: "2 hours after dose", explanation: "Incorrect. Too early for trough, too late for peak. This would be the correct answer for specific protocols." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "High Trough levels = Toxicity. The kidney needs a break (drug-free period) to recover.",
    pdfPage: 12,
  },
  {
    id: 20,
    category: "Neuromuscular Blockade Mechanism",
    questionText: "The neuromuscular blockade caused by aminoglycosides can be reversed by administering:",
    options: [
      { text: "Atropine", explanation: "Incorrect. For muscarinic blockade. This would be the correct answer for Organophosphate poisoning." },
      { text: "Calcium gluconate AND/OR Neostigmine", explanation: "Correct. Calcium overcomes the channel blockade; Neostigmine increases ACh levels." },
      { text: "Magnesium sulfate", explanation: "Incorrect. Mg worsens the blockade! This would be the correct answer for Torsades de Pointes." },
      { text: "Dantrolene", explanation: "Incorrect. This would be the correct answer for Malignant Hyperthermia." },
      { text: "Flumazenil", explanation: "Incorrect. This would be the correct answer for Benzodiazepine overdose." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Reversal of AG paralysis: Calcium + Neostigmine. (Magnesium makes it WORSE).",
    pdfPage: 12,
  },
  {
    id: 21,
    category: "Aminoglycosides: Excretion",
    questionText: "Aminoglycosides have a linear relationship between their clearance and:",
    options: [
      { text: "Liver enzymes (AST/ALT)", explanation: "Incorrect. Hepatic clearance is minimal. This would be the correct answer for Rifampin." },
      { text: "Creatinine Clearance (GFR)", explanation: "Correct. Distinct renal elimination via glomerular filtration." },
      { text: "Serum Albumin", explanation: "Incorrect. Binding is low. This would be the correct answer for Ceftriaxone." },
      { text: "Body fat percentage", explanation: "Incorrect. They don't enter fat. This would be the correct answer for Lipophilic drugs." },
      { text: "Urine pH", explanation: "Incorrect. Affects activity, not clearance. This would be the correct answer if asking about efficacy." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "AG Clearance ≈ GFR. If GFR drops, AG levels skyrocket.",
    pdfPage: 32,
  },
  {
    id: 22,
    category: "Clinical Scenarios: Peritonitis",
    questionText: "For a patient with a perforated bowel and peritonitis, Gentamicin must be combined with Clindamycin or Metronidazole. Why?",
    options: [
      { text: "Gentamicin cannot kill Gram-negatives in the gut", explanation: "Incorrect. It kills G- aerobes. This would be the correct answer if it was inactive." },
      { text: "Gentamicin has no activity against Anaerobes (Bacteroides)", explanation: "Correct. Peritonitis involves anaerobes. You must add anaerobic coverage." },
      { text: "To prevent nephrotoxicity", explanation: "Incorrect. This would be the correct answer if using a protectant." },
      { text: "To increase pH", explanation: "Incorrect. This would be the correct answer for Bicarb." },
      { text: "To treat fungal coinfection", explanation: "Incorrect. This would be the correct answer for Fluconazole." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Belly infection? Add Anaerobic coverage (Metro/Clinda). Gentamicin alone only covers the Aerobes.",
    pdfPage: 24,
  },
  {
    id: 23,
    category: "Aminoglycosides: Intracellular mechanism",
    questionText: "Once inside the cell, AGs bind to polysomes and primarily disrupt:",
    options: [
      { text: "Elongation only", explanation: "Incorrect. This would be the correct answer for Macrolides (translocation)." },
      { text: "Initiation of protein synthesis", explanation: "Correct. They freeze the initiation complex (30S-50S-mRNA)." },
      { text: "Termination", explanation: "Incorrect. This would be the correct answer for some other agents." },
      { text: "DNA replication", explanation: "Incorrect. This would be the correct answer for FQs." },
      { text: "Cell wall cross-linking", explanation: "Incorrect. This would be the correct answer for Beta-lactams." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Block Initiation -> Defective Proteins -> Dead Cell.",
    pdfPage: 20,
  },
  {
    id: 24,
    category: "Aminoglycosides: Toxicity Reversibility",
    questionText: "Which toxicity of aminoglycosides is most likely to be permanent (irreversible)?",
    options: [
      { text: "Nephrotoxicity", explanation: "Incorrect. Tubular cells regenerate. This would be the correct answer for reversible toxicity." },
      { text: "Neuromuscular blockade", explanation: "Incorrect. Reversible. This would be the correct answer for reversible acute toxicity." },
      { text: "Ototoxicity (Auditory)", explanation: "Correct. Hair cells do not regenerate." },
      { text: "Skin rash", explanation: "Incorrect. This would be the correct answer for many drugs (reversible)." },
      { text: "Nausea", explanation: "Incorrect. This would be the correct answer for transient side effects." },
    ],
    correctAnswerIndex: 2,
    clinicalPearl: "Kidneys heal, Ears do not. Deafness is forever.",
    pdfPage: 12,
  },
  {
    id: 25,
    category: "Aminoglycosides: Protein Binding",
    questionText: "Are Aminoglycosides highly protein bound?",
    options: [
      { text: "Yes, >90%", explanation: "Incorrect. This would be the correct answer for Ceftriaxone." },
      { text: "No, <10%", explanation: "Correct. They are free in the plasma." },
      { text: "Variable", explanation: "Incorrect. This would be the correct answer for other drugs." },
      { text: "Only in renal failure", explanation: "Incorrect. This would be the correct answer if uremia affected binding." },
      { text: "Only to albumin", explanation: "Incorrect. This would be the correct answer if it bound albumin specifically." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Low protein binding = High free drug concentration for filtration.",
    pdfPage: 13,
  },
  {
    id: 26,
    category: "Aminoglycosides: Inhalation",
    questionText: "Inhaled Tobramycin is used to manage:",
    options: [
      { text: "Asthma exacerbations", explanation: "Incorrect. Not indicated. This would be the correct answer for Albuterol/Steroids." },
      { text: "Pseudomonas colonization in Cystic Fibrosis", explanation: "Correct. Suppressive therapy." },
      { text: "Legionella pneumonia", explanation: "Incorrect. Intracellular pathogen. This would be the correct answer for Azithromycin (systemic)." },
      { text: "TB prophylaxis", explanation: "Incorrect. This would be the correct answer for Isoniazid." },
      { text: "Influenza", explanation: "Incorrect. Viral. This would be the correct answer for Oseltamivir." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "CF patients inhale Tobramycin (TOBI) to keep Pseudomonas in check.",
    pdfPage: 23,
  },
  {
    id: 27,
    category: "Aminoglycosides: CSF Penetration",
    questionText: "Generally, AGs have poor CSF penetration. When can they successfully treat meningitis when given IV?",
    options: [
      { text: "Always", explanation: "Incorrect. Generally poor penetration. This would be the correct answer for Ceftriaxone." },
      { text: "Only when meninges are inflamed (systemic inflammation)", explanation: "Correct. Inflammation increases BBB permeability, allowing some drug accumulation. (Note: Often still given intrathecally/intraventricularly for difficult cases). " },
      { text: "Never", explanation: "Incorrect. Can work with inflammation, but intrathecal often needed. This would be the correct answer for non-inflamed meninges (mostly)." },
      { text: "Only in neonates", explanation: "Incorrect. Not limited to neonates (actually risks kernicterus if asking about sulfonamides, but here risk is toxicity). This would be the correct answer if age-specific." },
      { text: "Only if given with Mannitol", explanation: "Incorrect. This would be the correct answer if osmotic disruption was used." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Meningitis needs high doses or intrathecal AGs because the BBB keeps them out.",
    pdfPage: 33,
  },
  {
    id: 28,
    category: "Aminoglycosides: Classification",
    questionText: "Spectinomycin is structurally related to aminoglycosides but is bacteriostatic. What is its only clinical use?",
    options: [
      { text: "Syphilis", explanation: "Incorrect. This would be the correct answer for Penicillin G." },
      { text: "Gonorrhea (in penicillin-allergic patients)", explanation: "Correct. An alternative for Gonorrhea, though rarely used now." },
      { text: "Chlamydia", explanation: "Incorrect. This would be the correct answer for Doxycycline." },
      { text: "Trichomoniasis", explanation: "Incorrect. This would be the correct answer for Metronidazole." },
      { text: "Scabies", explanation: "Incorrect. This would be the correct answer for Permethrin." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Spectinomycin -> Gonorrhea alternative.",
    pdfPage: 7,
  },
  {
    id: 29,
    category: "Aminoglycosides: Drug Interactions",
    questionText: "Concomitant use of Gentamicin with Loop Diuretics (Furosemide) increases the risk of:",
    options: [
      { text: "Hepatotoxicity", explanation: "Incorrect. This would be the correct answer for Tylenol." },
      { text: "Ototoxicity", explanation: "Correct. Loops are ototoxic (stria vascularis). AGs are ototoxic (hair cells). Double trouble." },
      { text: "Seizures", explanation: "Incorrect. This would be the correct answer for Carbapenems." },
      { text: "Bleeding", explanation: "Incorrect. This would be the correct answer for Warfarin." },
      { text: "Hyperkalemia", explanation: "Incorrect. This would be the correct answer for Spironolactone." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Gentamicin + Furosemide = Deafness risk. Be careful.",
    pdfPage: 30,
  },
  {
    id: 30,
    category: "Aminoglycosides: pH effect",
    questionText: "The antibacterial activity of Aminoglycosides is reduced in:",
    options: [
      { text: "Alkaline urine", explanation: "Incorrect. They work better in alkaline pH. This would be the correct answer if asking where they are most active." },
      { text: "Acidic environments (e.g., abscesses, acidic urine)", explanation: "Correct. Ionization state changes affect bacterial entry." },
      { text: "High oxygen tension", explanation: "Incorrect. This helps them. This would be the correct answer for increased activity." },
      { text: "Hyperglycemia", explanation: "Incorrect. This would be the correct answer if glucose interfered." },
      { text: "None of the above", explanation: "Incorrect. The second option is correct. This would be the correct answer if no option matched." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Acid kills AG efficacy. Alkaline urine boosts it.",
    pdfPage: 8,
  },
  {
    id: 31,
    category: "Clinical Scenarios: Burns",
    questionText: "Topical Gentamicin or Neomycin is often used in burn units to prevent infection by:",
    options: [
      { text: "Candida", explanation: "Incorrect. Fungal. This would be the correct answer for Nystatin." },
      { text: "Pseudomonas aeruginosa", explanation: "Correct. It is a major skin pathogen in burns." },
      { text: "Viruses", explanation: "Incorrect. This would be the correct answer for Acyclovir." },
      { text: "Anaerobes", explanation: "Incorrect. Not effective. This would be the correct answer for Metronidazole." },
      { text: "Mycoplasma", explanation: "Incorrect. No cell wall (irrelevant here) / Intracellular. This would be the correct answer for Macrolides." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Burns = Pseudomonas risk. Topical AGs help.",
    pdfPage: 24,
  },
  {
    id: 32,
    category: "Aminoglycosides: Half-life",
    questionText: "The typical serum half-life of an Aminoglycoside in a patient with normal renal function is:",
    options: [
      { text: "2-3 hours", explanation: "Correct. Short half-life, but long effect (PAE)." },
      { text: "12 hours", explanation: "Incorrect. This would be the correct answer for longer acting drugs." },
      { text: "24 hours", explanation: "Incorrect. This would be the correct answer for very long acting drugs." },
      { text: "30 minutes", explanation: "Incorrect. This would be the correct answer for very short acting drugs (e.g. Adenosine is seconds)." },
      { text: "1 week", explanation: "Incorrect. This would be the correct answer for Dalbavancin." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Short t1/2, Long PAE. (The Tortoise and the Hare).",
    pdfPage: 8,
  },
  {
    id: 33,
    category: "Aminoglycosides: Mechanism Detail",
    questionText: "The misreading of mRNA caused by AGs leads to the incorporation of:",
    options: [
      { text: "Lipids", explanation: "Incorrect. This would be the correct answer for fatty acid synthesis inhibitors." },
      { text: "Incorrect amino acids", explanation: "Correct. Producing non-functional or toxic proteins." },
      { text: "Glucose", explanation: "Incorrect. This would be the correct answer for glycogen." },
      { text: "DNA bases", explanation: "Incorrect. This would be the correct answer for nucleotide analogs." },
      { text: "ATP", explanation: "Incorrect. This would be the correct answer for energy metabolism." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Nonsense proteins kill the cell.",
    pdfPage: 9,
  },
  {
    id: 34,
    category: "Aminoglycosides: Enzymes",
    questionText: "The bacterial enzymes that inactivate AGs are located in the:",
    options: [
      { text: "Nucleus", explanation: "Incorrect. This would be the correct answer for DNA enzymes." },
      { text: "Periplasmic space", explanation: "Correct. In Gram-negatives, they intercept the drug before it reaches the ribosome." },
      { text: "Mitochondria", explanation: "Incorrect. This would be the correct answer for metabolic enzymes." },
      { text: "Extracellular fluid", explanation: "Incorrect. This would be the correct answer for secreted enzymes (like Beta-lactamases sometimes)." },
      { text: "Ribosome itself", explanation: "Incorrect. This would be the correct answer for target modification." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "The resistance enzymes wait in the periplasm like guards.",
    pdfPage: 22,
  },
  {
    id: 35,
    category: "Aminoglycosides: Clinical Use",
    questionText: "Which is a valid indication for Aminoglycoside monotherapy?",
    options: [
      { text: "Pneumococcal pneumonia", explanation: "Incorrect. Ineffective/Poor lung penetration. This would be the correct answer for Ceftriaxone." },
      { text: "Tularemia (Francisella tularensis)", explanation: "Correct. Streptomycin or Gentamicin is curative." },
      { text: "Staph aureus bacteremia", explanation: "Incorrect. Never mono. This would be the correct answer if combined with Nafcillin (historically)." },
      { text: "Anaerobic abscess", explanation: "Incorrect. Ineffective. This would be the correct answer for Metronidazole." },
      { text: "MRSA skin infection", explanation: "Incorrect. This would be the correct answer for Vancomycin." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Rarely used alone, EXCEPT for Tularemia and Plague.",
    pdfPage: 11,
  },
  {
    id: 36,
    category: "Aminoglycosides: Toxicity mechanism",
    questionText: "AGs accumulate in lysosomes of renal proximal tubular cells causing:",
    options: [
      { text: "Phospholipidosis and cell necrosis", explanation: "Correct. Lysosomal rupture triggers necrosis." },
      { text: "Apoptosis only", explanation: "Incorrect. Necrosis is the hallmark of ATN. This would be the correct answer for programmed cell death." },
      { text: "Hyperplasia", explanation: "Incorrect. This would be the correct answer for growth." },
      { text: "Metaplasia", explanation: "Incorrect. This would be the correct answer for tissue change." },
      { text: "Neoplasia", explanation: "Incorrect. This would be the correct answer for cancer." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Lysosomal clogging destroys the kidney cells.",
    pdfPage: 12,
  },
  {
    id: 37,
    category: "Aminoglycosides: Paromomycin",
    questionText: "Paromomycin is unique among AGs because it is used effectively against:",
    options: [
      { text: "Viruses", explanation: "Incorrect. This would be the correct answer for Antivirals." },
      { text: "Intestinal Protozoa (e.g., Entamoeba, Giardia, Cryptosporidium)", explanation: "Correct. It is luminal (non-absorbed) and active against parasites." },
      { text: "Fungi", explanation: "Incorrect. This would be the correct answer for Amphotericin." },
      { text: "Prions", explanation: "Incorrect. This would be the correct answer for nothing standard." },
      { text: "Helminths", explanation: "Incorrect. This would be the correct answer for Albendazole." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Paromomycin = Parasites (Entamoeba histolytica).",
    pdfPage: 11,
  },
  {
    id: 38,
    category: "Aminoglycosides: Volume of Distribution",
    questionText: "In a patient with ascites and edema, the Volume of Distribution (Vd) for Gentamicin will:",
    options: [
      { text: "Decrease", explanation: "Incorrect. This would be the correct answer for dehydration." },
      { text: "Increase", explanation: "Correct. Gentamicin distributes into extracellular water. More water (edema/ascites) = Larger tank to fill." },
      { text: "Stay the same", explanation: "Incorrect. This would be the correct answer if it bound tissue evenly (unlikely)." },
      { text: "Become zero", explanation: "Incorrect. Impossible." },
      { text: "Become negative", explanation: "Incorrect. Impossible." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Fluid overloaded? You need a bigger Loading Dose of Gentamicin.",
    pdfPage: 12,
  },
  {
    id: 39,
    category: "Aminoglycosides: Weight based dosing",
    questionText: "Because AGs do not distribute into adipose tissue, dosing in obese patients should use:",
    options: [
      { text: "Total Body Weight (TBW)", explanation: "Incorrect. Will overdose. This would be the correct answer if it distributed into fat." },
      { text: "Ideal Body Weight (IBW) or Adjusted Body Weight", explanation: "Correct. To avoid toxicity." },
      { text: "Height only", explanation: "Incorrect. This would be the correct answer for nothing." },
      { text: "BMI", explanation: "Incorrect. This would be the correct answer for classification." },
      { text: "Age", explanation: "Incorrect. This would be the correct answer for nothing." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Obese patient? Use Adjusted Body Weight. Don't dose the fat.",
    pdfPage: 8,
  },
  {
    id: 40,
    category: "Aminoglycosides: Vestibular Toxicity Symptoms",
    questionText: "Which symptom triad suggests vestibular toxicity?",
    options: [
      { text: "Vertigo, Nausea, Ataxia", explanation: "Correct. Room spinning, sickness, loss of balance." },
      { text: "Tinnitus, Hearing loss, Pain", explanation: "Incorrect. Auditory. This would be the correct answer for cochlear toxicity." },
      { text: "Rash, Fever, Eosinophilia", explanation: "Incorrect. Allergic. This would be the correct answer for drug allergy." },
      { text: "Oliguria, Azotemia, Proteinuria", explanation: "Incorrect. Renal. This would be the correct answer for nephrotoxicity." },
      { text: "Diplopia, Dysphagia, Dysarthria", explanation: "Incorrect. Neuromuscular. This would be the correct answer for Botulism/MG crisis." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Dizzy + Nauseous on Gentamicin? Stop the drug. Vestibular damage.",
    pdfPage: 12,
  },
  {
    id: 41,
    category: "Aminoglycosides: Mycobacteria",
    questionText: "Which aminoglycoside is specifically noted for its activity against *Mycobacterium avium-intracellulare* (MAC) complex?",
    options: [
      { text: "Amikacin", explanation: "Correct. Often used for NTM (Non-Tuberculous Mycobacteria)." },
      { text: "Neomycin", explanation: "Incorrect. This would be the correct answer for bowel prep." },
      { text: "Gentamicin", explanation: "Incorrect. Resistant often. This would be the correct answer for other G-." },
      { text: "Plazomycin", explanation: "Incorrect. This would be the correct answer for cUTI." },
      { text: "Spectinomycin", explanation: "Incorrect. This would be the correct answer for Gonorrhea." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Amikacin for MAC infections (HIV patients).",
    pdfPage: 24,
  },
  {
    id: 42,
    category: "Aminoglycosides: Eye Drops",
    questionText: "Gentamicin ophthalmic solution is commonly used for:",
    options: [
      { text: "Viral drug conjunctivitis", explanation: "Incorrect. This would be the correct answer for nothing." },
      { text: "Bacterial conjunctivitis", explanation: "Correct. Pink eye coverage." },
      { text: "Glaucoma", explanation: "Incorrect. This would be the correct answer for Timolol." },
      { text: "Cataracts", explanation: "Incorrect. This would be the correct answer for nothing topical AG related." },
      { text: "Dry eye", explanation: "Incorrect. This would be the correct answer for Artificial Tears." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Gentamicin eye drops = Bacterial Pink Eye coverage.",
    pdfPage: 11,
  },
  {
    id: 43,
    category: "Aminoglycosides: Neuromuscular Blockade Risks",
    questionText: "The risk of NM blockade is highest when AGs are given:",
    options: [
      { text: "Rapidly IV or in pleural/peritoneal spaces", explanation: "Correct. High local concentrations or rapid bolus precipitates the blockade." },
      { text: "Orally", explanation: "Incorrect. Not absorbed. This would be the correct answer for no effect." },
      { text: "Topically", explanation: "Incorrect. Low absorption. This would be the correct answer for low risk." },
      { text: "Slowly", explanation: "Incorrect. Safe method. This would be the correct answer for strict safety." },
      { text: "With food", explanation: "Incorrect. Irrelevant. This would be the correct answer for nothing." },
    ],
    correctAnswerIndex: 0,
    clinicalPearl: "Don't slam the IV Gentamicin. Infuse slowly.",
    pdfPage: 33,
  },
  {
    id: 44,
    category: "Aminoglycosides: Renal Recovery",
    questionText: "Unlike ototoxicity, AG-induced nephrotoxicity is usually:",
    options: [
      { text: "Irreversible", explanation: "Incorrect. This would be the correct answer for Ototoxicity." },
      { text: "Reversible", explanation: "Correct. Kidney cells have stem cells." },
      { text: "Fatal typically", explanation: "Incorrect. Only if ignored/dialysis unavailable. This would be the correct answer if untreated." },
      { text: "Untreatable", explanation: "Incorrect. This would be the correct answer for irreversible damage." },
      { text: "None of the above", explanation: "Incorrect. The second option is correct. This would be the correct answer if no option matched." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Kidneys bounce back. Ears don't. Prioritize the ears (once kidney injury is noted, modify/stop to save *both*).",
    pdfPage: 12,
  },
  {
    id: 45,
    category: "Aminoglycosides: Synergy Ratio",
    questionText: "For synergistic killing in endocarditis, the Aminoglycoside dose is typically:",
    options: [
      { text: "Higher than standard bactericidal dose", explanation: "Incorrect. Not needed. This would be the correct answer for Monotherapy." },
      { text: "Lower than standard, aiming for a Peak of 3-4 mcg/mL", explanation: "Correct. 'Synergy dosing' is lower because we just need enough to get inside the weakened wall." },
      { text: "Irrelevant", explanation: "Incorrect. This would be the correct answer if it didn't matter." },
      { text: "Massive", explanation: "Incorrect. Toxic. This would be the correct answer for nothing." },
      { text: "Given continuously", explanation: "Incorrect. This would be the correct answer for Beta-lactams." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Endocarditis Synergy = Low Dose Gentamicin.",
    pdfPage: 18,
  },
  {
    id: 46,
    category: "Aminoglycosides: Enteral Absoprtion Exception",
    questionText: "Can Aminoglycosides be absorbed from the gut in ANY circumstance?",
    options: [
      { text: "No, never", explanation: "Incorrect. Ulceration allows it. This would be the correct answer for intact mucosa." },
      { text: "Yes, if the mucosa is ulcerated or inflamed", explanation: "Correct. In severe colitis/IBD, some systemic absorption can occur due to barrier breakdown." },
      { text: "Yes, if taken with fat", explanation: "Incorrect. This would be the correct answer for Griseofulvin." },
      { text: "Yes, if taken with alcohol", explanation: "Incorrect. This would be the correct answer for nothing." },
      { text: "Yes, if taken with grapefruit juice", explanation: "Incorrect. CYP inhibition irrelevant. This would be the correct answer for Statins." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Ulcerated gut? Neomycin might leak into the blood. Watch out in severe IBD.",
    pdfPage: 11,
  },
  {
    id: 47,
    category: "Aminoglycosides: Ribosomal Selectivity",
    questionText: "Why do Aminoglycosides kill bacteria but not human cells?",
    options: [
      { text: "Humans have no ribosomes", explanation: "Incorrect. They do. This would be the correct answer for Viruses." },
      { text: "Humans have 80S ribosomes (60S+40S), bacteria have 70S (50S+30S)", explanation: "Correct. Structural differences prevent binding to mammalian ribosomes (mostly). Mitochondrial toxicity is a side note." },
      { text: "Humans degrade AGs instantly", explanation: "Incorrect. Renal elimination. This would be the correct answer for unstable drugs." },
      { text: "Humans have cell walls", explanation: "Incorrect. They don't. This would be the correct answer for Plants/Bacteria." },
      { text: "AGs don't enter human cells", explanation: "Incorrect. They do (kidney/ear). This would be the correct answer if they were totally extracellular." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Selectivity: 70S vs 80S. But Mitochondria look like bacteria (70S), hence toxicity!",
    pdfPage: 12,
  },
  {
    id: 48,
    category: "Aminoglycosides: Adaptive Resistance",
    questionText: "The 'First Exposure Effect' where bacteria temporarily survive AG exposure after the first dose is due to:",
    options: [
      { text: "Mutation", explanation: "Incorrect. Permanent. This would be the correct answer for genetic resistance." },
      { text: "Downregulation of uptake", explanation: "Correct. Adaptive resistance. This is why we wait (extended interval) - to let them reset." },
      { text: "Efflux", explanation: "Incorrect. Mechanistic but not the adaptive pause. This would be the correct answer for Tetracyclines." },
      { text: "Enzymes", explanation: "Incorrect. This is acquired resistance. This would be the correct answer for Transferases." },
      { text: "Biofilm", explanation: "Incorrect. Physical barrier. This would be the correct answer for chronic implants." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Adaptive Resistance: Bugs shut the door after the first hit. Wait for them to open it again (Q24H dosing).",
    pdfPage: 4,
  },
  {
    id: 49,
    category: "Aminoglycosides: Hearing Loss Frequency",
    questionText: "Ototoxicity initially affects:",
    options: [
      { text: "Low frequency sounds (Voice)", explanation: "Incorrect. This would be the correct answer for late stage." },
      { text: "High frequency sounds", explanation: "Correct. Basal turn of cochlea. Patients lose treble first." },
      { text: "All frequencies equally", explanation: "Incorrect. This would be the correct answer for conductive loss (sometimes)." },
      { text: "Middle ear pressure", explanation: "Incorrect. This would be the correct answer for Eustachian dysfunction." },
      { text: "Bone conduction only", explanation: "Incorrect. This would be the correct answer for nothing specific." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "High-frequency hearing goes first. Patients might not notice until it affects speech conversation.",
    pdfPage: 12,
  },
  {
    id: 50,
    category: "Aminoglycosides: Summary",
    questionText: "Which statement best summarizes Aminoglycosides?",
    options: [
      { text: "Safe, oral antibiotics for mild infections", explanation: "Incorrect. This would be the correct answer for Amoxicillin." },
      { text: "Toxic, parenteral antibiotics for severe Gram-negative aerobic infections", explanation: "Correct. Powerful but dangerous. Use with caution for aerobic G- bacilli." },
      { text: "Broad spectrum antibiotics for anaerobes", explanation: "Incorrect. This would be the correct answer for Metronidazole." },
      { text: "Antiviral agents", explanation: "Incorrect. This would be the correct answer for Acyclovir." },
      { text: "Antifungal agents", explanation: "Incorrect. This would be the correct answer for Fluconazole." },
    ],
    correctAnswerIndex: 1,
    clinicalPearl: "Aminoglycosides: The 'Mean' antibiotics. Mean to Gram Negatives, Mean to Kidneys, Mean to Ears.",
    pdfPage: 11,
  }
];
